Repository Infomaniak/android-kDrive, pull requests merged in 2021-10, with the labels that each got.

#291 Use biometric lib
  app/build.gradle
  app/src/main/java/com/infomaniak/drive/ui/LockActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/AppSecuritySettingsActivity.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
Labels: bug, enhancement

#292 Rename new upload file if same name exist
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
Labels: documentation, enhancement

#303 Fix file migration
  app/src/main/java/com/infomaniak/drive/data/cache/FileMigration.kt
Labels: bug

#304 Set the correct file
  app/src/main/java/com/infomaniak/drive/ui/home/ActivityFilesFragment.kt
Labels: bug
