Repository Infomaniak/android-kDrive, pull requests merged in 2021-07, with the labels that each got.

#114 fix upload file size
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
  app/src/main/java/com/infomaniak/drive/data/sync/UploadAdapter.kt
Labels: bug

#128 pictureFragment with realm cache
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomeViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesViewModel.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
Labels: bug

#129 no file found from preview
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewOtherFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPDFFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPictureFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewVideoFragment.kt
Labels: bug, enhancement

#131 fix realm on generatePath
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/ui/home/SwitchDriveDialog.kt
Labels: bug

#133 Tried to fix viewmodel bad state
  app/src/main/java/com/infomaniak/drive/ui/fileList/DownloadProgressDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderViewModel.kt
Labels: bug

#134 Fix open with
  app/src/main/java/com/infomaniak/drive/ui/fileList/DownloadProgressDialog.kt
Labels: bug

#137 Fix preview shared file
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/data/models/Rights.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalUriAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderAdapter.kt
  app/src/main/java/com/infomaniak/drive/utils/RealmListParceler.kt
Labels: bug, enhancement

#138 improve search files + refactor
  app/src/main/java/com/infomaniak/drive/ui/fileList/FavoritesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/ActivityFilesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/MySharesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/OfflineFileFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/SharedWithMeFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/TrashFragment.kt
Labels: enhancement

#141 fix realm list parcel if unavailable
  app/src/main/java/com/infomaniak/drive/utils/RealmListParceler.kt
Labels: bug

#142 fix AddFileBottomSheetDialog without file
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
Labels: bug

#143 migrate navHost to FragmentContainerView
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: bug, enhancement

#145 fix lost document persistable permission
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/utils/SyncUtils.kt
Labels: bug
