Repository Infomaniak/android-kDrive, pull requests merged in 2021-11, with the labels that each got.

#329 fix illegalState Exception on saving generated path
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
Labels: bug

#328 fix IllegalStateException on multiple selection action
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
Labels: bug

#326 recyclerview optimization
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
Labels: optimization

#332 Fix IllegalStateException on deletion a syncFile
  app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt
Labels: bug

#327 Fix load images in recyclerView and replace coil if needed - temp sol…
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/java/com/infomaniak/drive/ApplicationMain.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileActivitiesAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/AvailableShareableItemsAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/PermissionsAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/SharedItemsAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomePicturesAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/home/LastActivitiesAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesAdapter.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/java/com/infomaniak/drive/utils/OkHttpLibraryGlideModule.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
  app/src/main/res/drawable-night/fallback_image.xml
  app/src/main/res/drawable/fallback_image.xml
Labels: optimization

#334 Fix IllegalSateException on update a file
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
Labels: bug

#331 Fix IllegalStateException when a file is clicked
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
Labels: bug

#341 fix stable ids
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressFragment.kt
Labels: bug

#336 Removed auto-emptying of ShareLink.ValidUntil when Date was expired
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareLinkSettingsFragment.kt
Labels: enhancement

#342 load glide from file if only possible
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
Labels: bug

#335 Removed redirection when creating folder
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateCommonFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreatePrivateFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SelectFolderFragment.kt
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/navigation/select_folder.xml
Labels: bug

#330 Add FileManager actions in CloudStorage
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/data/documentprovider/CloudStorageProvider.kt
  app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/NewFolderViewModel.kt
  app/src/main/java/com/infomaniak/drive/utils/SyncUtils.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#346 Updated ShareLink texts
  app/src/main/java/com/infomaniak/drive/data/models/ShareLink.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/SelectPermissionBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsInfosFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareLinkSettingsFragment.kt
  app/src/main/java/com/infomaniak/drive/views/ShareLinkContainerView.kt
  app/src/main/res/layout/view_share_link_container.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#348 Fix pending folders userdrive
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt
  app/src/main/java/com/infomaniak/drive/data/models/UserDrive.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressFragment.kt
Labels: enhancement

#349 Activated MQTT only when in use
  app/src/main/java/com/infomaniak/drive/ApplicationMain.kt
  app/src/main/java/com/infomaniak/drive/data/services/BulkOperationWorker.kt
  app/src/main/java/com/infomaniak/drive/data/services/MqttClientWrapper.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/AccountUtils.kt
  app/src/main/java/com/infomaniak/drive/utils/BulkOperationsUtils.kt
Labels: enhancement

#351 Fixed common folder creating in the wrong location
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateCommonFolderFragment.kt
Labels: bug

#354 ignore stable id if position doesn't exists
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
Labels: bug

#353 Added notification for BatteryOptimization
  app/src/main/java/com/infomaniak/drive/data/documentprovider/CloudStorageProvider.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#356 remove sharing file from argument in preview
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
Labels: bug, optimization

#355 Remove upload realm listener
  app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
Labels: bug

#360 fix documentProvider columns from ACTION_OPEN_DOCUMENT
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
Labels: bug, enhancement

#358 Fix download and duplicate right
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
Labels: bug

#362 Removed useless `+` in XML
  app/src/main/res/layout/activity_lock.xml
  app/src/main/res/layout/activity_no_drive.xml
  app/src/main/res/layout/cardview_home_file_activity.xml
  app/src/main/res/layout/cardview_permission.xml
  app/src/main/res/layout/fragment_bottom_sheet_information.xml
  app/src/main/res/layout/fragment_bottom_sheet_sort_files.xml
  app/src/main/res/layout/fragment_create_folder.xml
  app/src/main/res/layout/fragment_file_details_infos.xml
  app/src/main/res/layout/fragment_file_share_link_settings.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_intro.xml
  app/src/main/res/layout/fragment_menu.xml
  app/src/main/res/layout/fragment_settings_about.xml
  app/src/main/res/layout/item_dropbox_settings.xml
  app/src/main/res/layout/item_file.xml
  app/src/main/res/layout/item_file_activity.xml
  app/src/main/res/layout/item_file_comment.xml
  app/src/main/res/layout/item_shareable_item.xml
  app/src/main/res/layout/view_network_unavailable_home.xml
  app/src/main/res/layout/view_not_enough_storage.xml
  app/src/main/res/layout/view_url_display.xml
Labels: enhancement

#363 fix fragment_home.xml inconsistency
  app/src/main/res/layout/fragment_home.xml
Labels: bug, enhancement

#366 Fix add file in realm from activities
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SelectFolderActivity.kt
Labels: bug

#364 fix file equals fun with a deleted file
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
Labels: bug

#370 Fix duplicate files from a folder files
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
Labels: bug

#369 Multiple bug fix
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/DownloadProgressDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
Labels: bug

#373 fix navigation controller state on restore activity
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
Labels: bug

#374 fix exoplayer deprecated methods
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewVideoFragment.kt
Labels: enhancement

#375 ignore duplicate files from realm live files
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
Labels: bug

#376 fix navController
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
Labels: bug

#387 Fix current Uploads count for the current drive
  app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt
Labels: bug

#377 Categories #01: Added Models
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/drive/data/cache/DriveInfosController.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileMigration.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/data/models/FileCategory.kt
  app/src/main/java/com/infomaniak/drive/data/models/drive/Category.kt
  app/src/main/java/com/infomaniak/drive/data/models/drive/CategoryRights.kt
  app/src/main/java/com/infomaniak/drive/data/models/drive/Drive.kt
  app/src/main/java/com/infomaniak/drive/utils/RealmListParceler.kt
  app/src/main/java/com/infomaniak/drive/utils/RealmModules.kt
Labels: feature

#378 Categories #02: Display in FileInfo
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsInfosFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/java/com/infomaniak/drive/views/CategoriesContainerView.kt
  app/src/main/res/drawable/ic_category.xml
  app/src/main/res/layout/fragment_file_details_infos.xml
  app/src/main/res/layout/view_categories_container.xml
Labels: feature

#379 Categories #03: Display in FileList
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/java/com/infomaniak/drive/views/CategoryIconView.kt
  app/src/main/res/layout/cardview_file_grid.xml
  app/src/main/res/layout/item_category_icon.xml
  app/src/main/res/layout/item_file.xml
  app/src/main/res/values/dimens.xml
Labels: feature

#381 Categories #05: Display in Activities
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/data/models/FileActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/SelectCategoriesBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/java/com/infomaniak/drive/utils/RealmListParceler.kt
Labels: feature

#382 Categories #06: Management in FileAction
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsInfosFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
  app/src/main/res/layout/view_file_info_actions.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: feature

#385 Categories #09: Added Information panel
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/drive/data/models/AppSettings.kt
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/CategoriesInformationBottomSheetDialog.kt
  app/src/main/res/drawable/img_categories_en.png
  app/src/main/res/drawable/img_categories_fr.png
  app/src/main/res/layout/fragment_bottom_sheet_categories_information.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: feature

#388 Categories #10: Updated RealmObject to Embedded
  app/src/main/java/com/infomaniak/drive/data/cache/DriveInfosController.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileMigration.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/data/models/FileCategory.kt
  app/src/main/java/com/infomaniak/drive/data/models/Rights.kt
  app/src/main/java/com/infomaniak/drive/data/models/drive/Category.kt
  app/src/main/java/com/infomaniak/drive/data/models/drive/CategoryRights.kt
  app/src/main/java/com/infomaniak/drive/data/models/drive/Drive.kt
  app/src/main/java/com/infomaniak/drive/data/models/drive/DrivePackFunctionality.kt
  app/src/main/java/com/infomaniak/drive/data/models/drive/DrivePreferences.kt
  app/src/main/java/com/infomaniak/drive/data/models/drive/DriveTeamsCategories.kt
  app/src/main/java/com/infomaniak/drive/data/models/drive/DriveUsersCategories.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/CreateOrEditCategoryBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/utils/DriveDeserializer.kt
  app/src/main/java/com/infomaniak/drive/utils/FileDeserializer.kt
Labels: feature
