Repository Infomaniak/android-kDrive, pull requests merged in 2021-09, with the labels that each got.

#226 fix total byte written in the old versions
  app/src/main/java/com/infomaniak/drive/data/api/ProgressOutputStream.kt
Labels: bug

#233 on api upload error, restart the upload
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
Labels: bug

#234 stop the errors on some cases
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
Labels: bug

#229 remove save path transaction from main ui
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
Labels: bug

#230 delete only if realm object is valid
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
Labels: bug

#243 Hide folder progress if necessary
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
Labels: bug, enhancement

#239 Avoid duplicate upload worker
  app/src/main/java/com/infomaniak/drive/data/services/PeriodicUploadWorker.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
  app/src/main/java/com/infomaniak/drive/utils/SyncUtils.kt
Labels: bug

#249 Fix null fileModifiedAt and send sentry message if is null
  app/src/main/java/com/infomaniak/drive/utils/SyncUtils.kt
Labels: bug

#258 Actually /sdcard/Android/media⁠ directory is part of shared storage
  app/src/main/AndroidManifest.xml
Labels: help wanted

#260 Upload in shared with me
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/NewFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/FileSubTypeListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/SharedWithMeFragment.kt
Labels: enhancement

#255 Fix shareable link
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsInfosFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/views/ShareLinkContainerView.kt
Labels: bug

#257 Fix sync offlines
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/data/services/DownloadWorker.kt
Labels: bug

#256 Content observe delay
  app/src/main/java/com/infomaniak/drive/data/sync/FileObserveService.kt
  app/src/main/java/com/infomaniak/drive/data/sync/FileObserveServiceApi24.kt
  app/src/main/java/com/infomaniak/drive/data/sync/UploadNotifications.kt
  app/src/main/java/com/infomaniak/drive/utils/SyncUtils.kt
Labels: enhancement

#266 clear back stack after reselect item from bottom navigation
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
Labels: enhancement

#268 fix delete all uploads after close all uploads button clicked
  app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt
  app/src/main/java/com/infomaniak/drive/data/sync/UploadNotifications.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug

#270 Fix upload in progress view
  app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/SyncUtils.kt
Labels: bug

#271 Retry on api upload error
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
Labels: bug

#273 ignore file without size in device local storage
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
Labels: bug

#272 Show uploadNetworkErrorWifiRequired in UploadInProgressFragment
  app/src/main/java/com/infomaniak/drive/data/sync/UploadNotifications.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/SyncUtils.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
Labels: enhancement

#276 Fix improve upload notifications
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
  app/src/main/java/com/infomaniak/drive/utils/NotificationUtils.kt
Labels: bug
