Repository Infomaniak/android-kDrive, pull requests merged in 2022-07, with the labels that each got.

#836 refresh root folder from remote if needed
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
Labels: bug, api-v2

#838 opt out of scoped storage on android Q
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
Labels: bug

#841 Multi fix
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomeOfflineFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesFragment.kt
  app/src/main/java/com/infomaniak/drive/views/ShareLinkContainerView.kt
Labels: bug

#844 Fix remove category
  app/src/androidTest/java/com/infomaniak/drive/ApiRepositoryTest.kt
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/SelectCategoriesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/SelectCategoriesViewModel.kt
  app/src/main/res/layout/fragment_file_details_infos.xml
Labels: bug

#846 Fix file details status bar
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt
Labels: bug

#847 Upload optimization
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
  app/src/main/java/com/infomaniak/drive/data/models/upload/UploadSegment.kt
  app/src/main/java/com/infomaniak/drive/data/models/upload/ValidChunks.kt
Labels: enhancement

#848 Add Scan document
  .idea/navEditor.xml
  app/build.gradle
  app/src/main/java/com/infomaniak/drive/ApplicationMain.kt
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/utils/GeniusScanUtils.kt
  app/src/main/res/layout/fragment_bottom_sheet_add_file.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/raw/deu.traineddata
  app/src/main/res/raw/eng.traineddata
  app/src/main/res/raw/fra.traineddata
  app/src/main/res/raw/ita.traineddata
  app/src/main/res/raw/spa.traineddata
  app/src/main/res/xml/exposed_files_path.xml
  build.gradle
Labels: feature

#851 update exoplayer lib to 2.18.1
  app/build.gradle
Labels: enhancement

#853 Update upload api errors - Waiting for the production of the api
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
Labels: enhancement, api-v2

#849 copy document provider files in caches before to upload
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/ImportFilesDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressViewModel.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/java/com/infomaniak/drive/utils/SyncUtils.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
  app/src/main/res/layout/dialog_import_files.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#855 Show preview file in multiselect mode
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
Labels: enhancement

#857 Add Camera permission
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/utils/CameraPermissions.kt
  app/src/main/java/com/infomaniak/drive/utils/DrivePermissions.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug

#856 Fix any folder found in upload in progress
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressViewModel.kt
Labels: bug

#859 Fix share files success and failed in UploadWorker
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
  app/src/main/java/com/infomaniak/drive/data/sync/UploadNotifications.kt
Labels: bug

#860 Refactor drive url
  app/build.gradle
  app/src/main/java/com/infomaniak/drive/ApplicationMain.kt
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
Labels: enhancement

#861 migrate create document file from cloud storage to api v2
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/drive/data/documentprovider/CloudStorageProvider.kt
Labels: api-v2
