Repository Infomaniak/android-kDrive, pull requests merged in 2022-03, with the labels that each got.

#602 Factorize multi select layout
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/MenuPicturesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesFragment.kt
  app/src/main/res/layout/fragment_file_list.xml
  app/src/main/res/layout/fragment_menu_pictures.xml
  app/src/main/res/layout/fragment_pictures.xml
  app/src/main/res/layout/multi_select_layout.xml
Labels: enhancement

#604 Improve upload notifications
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
Labels: bug, enhancement

#608 Transparent statusbar
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/java/com/infomaniak/drive/views/CollapsingSubTitleToolbarBehavior.kt
  app/src/main/res/layout/fragment_preview_slider.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values-v27/styles.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#605 limit upload process to available memory in the heap
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
Labels: bug, enhancement

#626 Fixed invisible navbar icons
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
Labels: bug

#611 fix test crash at setup
  app/src/androidTest/java/com/infomaniak/drive/FileControllerTest.kt
  app/src/androidTest/java/com/infomaniak/drive/KDriveTest.kt
  app/src/androidTest/java/com/infomaniak/drive/ui/EspressoHomeUiTest.kt
  app/src/androidTest/java/com/infomaniak/drive/ui/FileItemUiTest.kt
  app/src/androidTest/java/com/infomaniak/drive/ui/FileListUiTest.kt
  app/src/androidTest/java/com/infomaniak/drive/ui/HomeUiTest.kt
  app/src/androidTest/java/com/infomaniak/drive/ui/KDriveUiTest.kt
  app/src/androidTest/java/com/infomaniak/drive/ui/MenuUiTest.kt
  app/src/main/java/com/infomaniak/drive/utils/AccountUtils.kt
Labels: bug

#607 Factorized bulk operations
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/drive/data/models/BulkOperationType.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/ActionMultiSelectBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/FileListMultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectManager.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/PicturesMultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/MenuPicturesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesFragment.kt
  app/src/main/res/layout/fragment_bottom_sheet_multi_select_actions.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: enhancement, optimization

#615 Fixed Pictures autoscroll & duplication when coming back from Preview
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesFragment.kt
Labels: bug

#624 Refactor so SonarCloud is happy
  app/src/main/java/com/infomaniak/drive/utils/AccountUtils.kt
  app/src/main/java/com/infomaniak/drive/views/com/liuzhenlin/simrv/SlidingItemMenuRecyclerView.kt
Labels: optimization

#617 Fixed SelectAllButton blinking in FileList multiselect
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
Labels: bug

#628 Fixed back navigation button in the Image tab
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesFragment.kt
Labels: bug

#629 Fixed endless spinning in Pictures list when changing theme
  app/src/main/java/com/infomaniak/drive/ui/menu/MenuPicturesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesViewModel.kt
Labels: bug

#632 Fixed missing month label in gallery on rare occasions
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesAdapter.kt
Labels: bug

#613 Updated Matomo for MultiSelect
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/FileListMultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/PicturesMultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/MatomoUtils.kt
Labels: enhancement

#635 Fix shimmering in gallery not being displayed correctly
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesAdapter.kt
Labels: bug

#634 Fixed Home tabs fragments that were recreated all the time
  app/src/main/java/com/infomaniak/drive/ui/home/HomeFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesFragment.kt
Labels: bug

#637 Fixed NPE in PreviewSlider when getting categories
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
Labels: bug

#639 prevent screen from locking when video is playing
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewVideoFragment.kt
Labels: enhancement

#641 Fix multi selection issue when clicking on checkmark in gallery
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesAdapter.kt
Labels: bug

#646 Fix load big image from local storage
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPictureFragment.kt
Labels: bug, enhancement

#647 fix import for video taken by user
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
Labels: bug

#621 Added Files exceptions in Multi-Select feature
  app/src/main/java/com/infomaniak/drive/data/models/BulkOperation.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectManager.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesFragment.kt
Labels: enhancement

#650 Fixed Bulk actions broken notification
  app/src/main/java/com/infomaniak/drive/data/models/BulkOperationType.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareLinkSettingsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
Labels: bug

#657 Fixed Pictures not displayed in Gallery when connectivity isn't available
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesViewModel.kt
Labels: bug

#655 Migrate to coil 2.0
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/java/com/infomaniak/drive/ApplicationMain.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileActivitiesAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/AvailableShareableItemsAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/PermissionsAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/SharedItemsAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPictureFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/LastActivitiesAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesAdapter.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/java/com/infomaniak/drive/utils/FileItemUtils.kt
  app/src/main/java/com/infomaniak/drive/utils/OkHttpLibraryGlideModule.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
Labels: enhancement

#652 Fix edge to edge mode
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
Labels: bug

#667 Hide set offline in multiselect when 'all selected' is used
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectManager.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: bug

#664 fix path location from file details
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
Labels: bug

#663 first fix and add more sentry logs for the null folder when 1 folder …
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressFragment.kt
Labels: bug, help wanted, can't reproduce

#668 Add Espresso viewAction to wait with timeout until views are shown
  app/src/androidTest/java/com/infomaniak/drive/ui/FileItemUiTest.kt
  app/src/androidTest/java/com/infomaniak/drive/ui/FileListUiTest.kt
  app/src/androidTest/java/com/infomaniak/drive/ui/HomeUiTest.kt
  app/src/androidTest/java/com/infomaniak/drive/ui/KDriveUiTest.kt
  app/src/androidTest/java/com/infomaniak/drive/ui/MenuUiTest.kt
Labels: bug

#674 Clean multi select
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectManager.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesFragment.kt
Labels: enhancement

#673 Fixed "Select All" exceptions
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
Labels: bug

#675 Used only Bulk actions for MultiSelect when SelectAll is used
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectManager.kt
Labels: enhancement

#552 Add ooform support
  app/src/main/java/com/infomaniak/drive/data/models/ConvertedType.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/SearchFilterTypeBottomSheetDialog.kt
  app/src/main/res/drawable/ic_file_form.xml
  app/src/main/res/layout/fragment_bottom_sheet_add_file.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#678 Added a "Go to parent folder" action in Files menu
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsInfoFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
  app/src/main/res/layout/view_file_info_actions.xml
Labels: enhancement

#683 Correctly stops BottomSheet when expanded in PreviewSlider
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/res/layout/fragment_preview_slider.xml
Labels: bug

#685 Fix collapsing toolbar threshold
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/views/CollapsingSubTitleToolbarBehavior.kt
  app/src/main/res/layout/fragment_file_details.xml
Labels: enhancement

#687 Cleaned MultiSelect feature before adding it in Trash
  app/src/main/java/com/infomaniak/drive/data/models/BulkOperationType.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/FileListMultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/TrashFragment.kt
Labels: enhancement

#688 Folders info now display the contained file and folder count
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/ColorFolderUpgradeBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/DropBoxBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/SecureLinkShareBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsInfoFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsViewModel.kt
  app/src/main/res/layout/fragment_file_details_infos.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#710 Fix FileUriExposedException and exposed uri only for office file.
  app/src/main/java/com/infomaniak/drive/ApplicationMain.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
Labels: bug

#715 Fix current progress ui in FileAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
Labels: bug

#704 Fix unsupported characters
  app/src/main/java/com/infomaniak/drive/data/models/Shareable.kt
  app/src/main/java/com/infomaniak/drive/data/sync/UploadNotifications.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/java/com/infomaniak/drive/utils/NotificationUtils.kt
  app/src/main/java/com/infomaniak/drive/utils/SyncUtils.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug

#716 Fix upload buffer size <= 0
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
Labels: bug, enhancement

#714 Fix Common Folders icon & icon color
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/utils/FileItemUtils.kt
Labels: enhancement

#686 MultiSelect in Trash
  app/src/main/java/com/infomaniak/drive/data/models/BulkOperationType.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/TrashedFileActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SelectFolderActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/TrashMultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/FileSubTypeListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/MenuPicturesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/TrashFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/TrashViewModel.kt
  app/src/main/java/com/infomaniak/drive/views/NoItemsLayoutView.kt
  app/src/main/res/layout/fragment_bottom_sheet_multi_select_actions.xml
  app/src/main/res/layout/multi_select_layout.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#702 MultiSelect fixes
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
  app/src/main/res/layout/fragment_bottom_sheet_multi_select_actions.xml
Labels: bug
