Repository Infomaniak/android-kDrive, pull requests merged in 2022-04, with the labels that each got.

#703 MultiSelect everywhere
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FavoritesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/FavoritesMultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MySharesMultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/OfflineMultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/RecentChangesMultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/SharedWithMeMultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomeOfflineFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/FileSubTypeListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/MySharesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/OfflineFileFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/RecentChangesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/SharedWithMeFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/TrashFragment.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: feature

#731 Tablets optimizations
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
  app/src/main/java/com/infomaniak/drive/utils/FileItemUtils.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/cardview_folder_grid.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/view_no_items.xml
Labels: bug, enhancement

#708 Fix MultiSelect download outside of default FileList
  app/src/main/java/com/infomaniak/drive/ui/fileList/FavoritesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/TrashMultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/MenuPicturesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/MySharesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/OfflineFileFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/RecentChangesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/SharedWithMeFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/TrashFragment.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: enhancement

#719 Update actions order to be the same everywhere
  app/src/main/res/layout/fragment_bottom_sheet_multi_select_actions.xml
  app/src/main/res/layout/view_file_info_actions.xml
Labels: enhancement

#718 Fix pending files doesn't disappear - issue #713
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
Labels: bug

#735 fix typo
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/TrashedFileActionsBottomSheetDialog.kt
Labels: bug

#725 fix pop stack in preview
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateCommonFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateDropBoxFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreatePrivateFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/NotSupportedExtensionBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/TrashedFileActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/ConvertToDropBoxFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/DownloadProgressDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/ManageDropboxFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsCommentsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsInfoFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareLinkSettingsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomeActivitiesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/TrashFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
Labels: bug

#717 fix first recent changes download
  app/src/main/java/com/infomaniak/drive/ui/menu/RecentChangesViewModel.kt
Labels: bug

#746 Add upload priority
  app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
Labels: enhancement

#737 Add dialog to inform user about battery usage of the app's background functioning - DontKillMyApp
  app/src/main/java/com/infomaniak/drive/data/models/UiSettings.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/BackgroundSyncPermissionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/utils/DrivePermissions.kt
  app/src/main/res/drawable-night/ic_background_sync.xml
  app/src/main/res/drawable/ic_alert_triangle.xml
  app/src/main/res/drawable/ic_background_sync.xml
  app/src/main/res/layout/fragment_bottom_sheet_background_sync.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#760 Multiple quick fix
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/data/models/UiSettings.kt
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/BackgroundSyncPermissionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/CategoriesInformationBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/utils/DrivePermissions.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/res/drawable-fr-hdpi/new_feature_categories.png
  app/src/main/res/drawable-fr-mdpi/new_feature_categories.png
  app/src/main/res/drawable-fr-xhdpi/new_feature_categories.png
  app/src/main/res/drawable-fr-xxhdpi/new_feature_categories.png
  app/src/main/res/drawable-fr-xxxhdpi/new_feature_categories.png
  app/src/main/res/drawable-hdpi/new_feature_categories.png
  app/src/main/res/drawable-mdpi/new_feature_categories.png
  app/src/main/res/drawable-xhdpi/new_feature_categories.png
  app/src/main/res/drawable-xxhdpi/new_feature_categories.png
  app/src/main/res/drawable-xxxhdpi/new_feature_categories.png
  app/src/main/res/layout/activity_save_external_file.xml
  app/src/main/res/layout/dialog_name_prompt.xml
  app/src/main/res/layout/fragment_bottom_sheet_categories_information.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement
