Repository Infomaniak/android-kDrive, pull requests merged in 2022-01, with the labels that each got.

#409 Fixed File not compiling
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/FilePresenter.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
Labels: bug

#423 fix sharedWithMe regression in MenuFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/MenuFragment.kt
Labels: bug

#420 fix navigations from FileShareDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareDetailsFragment.kt
Labels: bug

#419 Load all uri in RecyclerView at once from SaveExternalUriAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalUriAdapter.kt
  app/src/main/res/layout/activity_save_external_file.xml
Labels: bug

#427 fix bottomsheet item not reselected with custom
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/utils/NavigationUiUtils.kt
Labels: bug

#421 Fix remove from favorite fragment
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FavoritesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/FileSubTypeListFragment.kt
  app/src/main/java/com/infomaniak/drive/views/TimeInputView.kt
Labels: bug, enhancement

#424 Fix menu in sharewithme
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/CreateOrEditCategoryFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/SelectCategoriesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
Labels: bug

#430 Fix not shared dropbox activity + refactor activities
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
Labels: bug

#434 Fixed ClearFilters & CategoriesOwnership
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFiltersFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFiltersViewModel.kt
Labels: bug

#436 Force reload files after 3 months
  app/src/main/java/com/infomaniak/drive/data/cache/DriveInfosController.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt
Labels: enhancement

#435 Upload with dynamic size
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
  app/src/main/java/com/infomaniak/drive/data/sync/UploadNotifications.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#437 Fixed a bug in ShareLink for Office files
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/SelectPermissionBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsInfosFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareAddUserDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareLinkSettingsFragment.kt
Labels: bug

#453 Added CODEOWNERS file for auto-reviews
  .github/CODEOWNERS
Labels: enhancement

#432 Refactor SearchFragment + Added SearchViewModel
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFiltersFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchViewModel.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: enhancement

#449 Fix shared preview slider view model
  app/build.gradle
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewOtherFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPDFFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPictureFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewVideoFragment.kt
Labels: bug

#448 Cleaned code
  app/src/main/java/com/infomaniak/drive/data/api/ProgressRequestBody.kt
  app/src/main/java/com/infomaniak/drive/data/api/ProgressResponseBody.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/data/documentprovider/DocumentCursor.kt
  app/src/main/java/com/infomaniak/drive/data/services/DownloadWorker.kt
  app/src/main/java/com/infomaniak/drive/data/sync/FileObserveService.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateDropBoxFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SelectFolderActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsInfosFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/SharedItemsAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/login/MigrationActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SyncSettingsActivity.kt
  app/src/main/java/com/infomaniak/drive/utils/DrivePermissions.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/java/com/infomaniak/drive/utils/FormatterFileSize.kt
  app/src/main/java/com/infomaniak/drive/utils/OkHttpLibraryGlideModule.kt
  app/src/main/java/com/infomaniak/drive/utils/RebootReceiver.kt
  app/src/main/java/com/infomaniak/drive/views/CollapsingSubTitleToolbarBehavior.kt
  app/src/main/java/com/infomaniak/drive/views/ShareLinkContainerView.kt
  app/src/main/java/com/infomaniak/drive/views/com/liuzhenlin/simrv/SlidingItemMenuRecyclerView.kt
Labels: enhancement

#446 Fixed navigation issue when creating a Dropbox or Common folder
  app/src/main/java/com/infomaniak/drive/data/cache/DriveInfosController.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateCommonFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateDropBoxFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreatePrivateFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/NewFolderViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareViewModel.kt
Labels: bug

#457 Manage multiple files names from SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalUriAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressFragment.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
  app/src/main/res/layout/activity_save_external_file.xml
  app/src/main/res/layout/item_file_name.xml
Labels: enhancement

#471 Fixed Categories rights in Shared folders
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsInfoFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/views/CategoriesContainerView.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
Labels: bug

#459 Home offline large list
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomeOfflineFragment.kt
  app/src/main/res/drawable/ic_largelist.xml
Labels: enhancement

#463 Added the big 'open with' button when filetype can't be previewed
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewOtherFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPictureFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewVideoFragment.kt
  app/src/main/res/layout/fragment_preview_others.xml
Labels: enhancement

#466 Refactor ShareLink
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/CreateOrEditCategoryFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsInfoFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/SelectCategoriesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/views/CategoriesContainerView.kt
  app/src/main/java/com/infomaniak/drive/views/ShareLinkContainerView.kt
Labels: enhancement

#467 Fixed CreateCategory rights issue in SelectedCategories screen
  app/src/main/java/com/infomaniak/drive/data/cache/DriveInfosController.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/CategoryInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFiltersFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsInfoFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/SelectCategoriesFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: bug

#474 add right migration sentry logs
  app/src/main/java/com/infomaniak/drive/data/cache/FileMigration.kt
Labels: bug, can't reproduce

#473 Refactor Bulk Actions
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
Labels: enhancement

#477 Fixed Share observable issue in FileDetailsInfo
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsActivitiesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsCommentsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsInfoFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsViewModel.kt
Labels: bug

#475 Pictures backup custom date
  app/src/main/java/com/infomaniak/drive/data/models/SyncSettings.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareLinkSettingsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SelectSaveDateBottomSheetAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SelectSaveDateBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SyncSettingsActivity.kt
  app/src/main/java/com/infomaniak/drive/views/DateInputView.kt
  app/src/main/java/com/infomaniak/drive/views/TimeInputView.kt
  app/src/main/res/layout/activity_sync_settings.xml
  app/src/main/res/layout/view_date_input.xml
  app/src/main/res/layout/view_time_input.xml
Labels: enhancement

#481 Used `getTintedDrawable` function everywhere
  app/src/main/java/com/infomaniak/drive/ui/SwitchDriveBottomSheetAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateCommonFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateDropBoxFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/DropBoxResultBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/SearchFilterTypeBottomSheetAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFiltersAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFiltersFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareAddUserDialog.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/res/layout/fragment_new_folder.xml
Labels: enhancement

#489 Removed FolderColor activities
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
Labels: bug

#485 Fixed FolderCreation button not clickable when the view is recreated
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateCommonFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateDropBoxFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreatePrivateFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/NewFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/NewFolderViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/SelectPermissionBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/PermissionsAdapter.kt
  app/src/main/res/layout/cardview_permission.xml
Labels: bug
