Repository Infomaniak/android-kDrive, pull requests merged in 2022-08, with the labels that each got.

#864 Fix SaveExternal if folderId is -1
  app/src/main/java/com/infomaniak/drive/data/models/UiSettings.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
Labels: bug

#865 Multiples fix
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/ImportFilesDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
Labels: bug

#866 fix mediastore file size in SaveExternalFilesActivity
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
Labels: bug

#868 Remove "onActivityResult" and refactor scan implementation
  app/build.gradle
  app/src/fdroid/java/com/infomaniak/drive/GeniusScanUtils.kt
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/preprod/java/com/infomaniak/drive/GeniusScanUtils.kt
  app/src/standard/java/com/infomaniak/drive/GeniusScanUtils.kt
Labels: optimization

#867 Log if Refresh Token Error and fix api error code
  app/src/main/java/com/infomaniak/drive/ApplicationMain.kt
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/MenuFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/SyncUtils.kt
Labels: bug

#871 Update api for FileConversion to FileConversionCapabilities
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/data/models/file/FileConversion.kt
Labels: optimization

#872 Attempt to fix a Viewpager bug
  app/src/main/res/layout/fragment_preview_others.xml
  app/src/main/res/layout/fragment_preview_pdf.xml
  app/src/main/res/layout/fragment_preview_video.xml
Labels: bug

#873 Fix lifecycle save external orientation
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
Labels: bug

#874 Handle null extras in SaveExternalFilesActivity and share sentry logs
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
Labels: bug

#876 Ignore sentry is SecurityException-ACTION_OPEN_DOCUMENT
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
Labels: optimization

#878 Fix UnsupportedOperationException from SaveExternalFilesActivity
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
Labels: bug

#877 Fix current file not init in preview
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewVideoFragment.kt
Labels: bug

#879 Make sure the right file size in UploadWorker from mediaStore
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
Labels: bug, enhancement

#880 close upload session for each reset upload token operation
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
Labels: bug, enhancement

#881 Keep root children file when force refresh
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
Labels: bug

#882 Get fileName from an uri when no display name has been found in MediaStore
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalUriAdapter.kt
Labels: bug

#886 Add sentry log and fix non uri in extra SaveExternalFilesActivity
  app/build.gradle
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
Labels: bug

#887 Temporary fix for RealmFileException in uploadWorker
  app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt
Labels: bug

#888 Refactor intent
  app/src/main/java/com/infomaniak/drive/ApplicationMain.kt
  app/src/main/java/com/infomaniak/drive/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/DrivePermissions.kt
Labels: optimization
