Repository Infomaniak/android-kDrive, pull requests merged in 2022-06, with the labels that each got.

#798 Fix deleted document provider file
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
Labels: bug

#781 Fix moved files not being removed from preview in file list
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
Labels: bug

#786 Can now click on a folder from the home activities to move to it
  app/src/main/java/com/infomaniak/drive/ui/home/HomeActivitiesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/LastActivitiesAdapter.kt
Labels: enhancement

#794 Folder sharing link can now be shared instead of copied
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
  app/src/main/res/layout/view_file_info_actions.xml
  app/src/main/res/layout/view_url_display.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#783 Added move files to multiselection "3 dots" menu
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SelectFolderActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/SharedWithMeMultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/TrashMultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SyncSettingsActivity.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
  app/src/main/res/layout/fragment_bottom_sheet_multi_select_actions.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: enhancement

#796 Fixed multi select wrong number of selected items bug
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectManager.kt
Labels: bug

#812 Fix lock app
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
Labels: enhancement

#807 Path folder navigate if not available
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsInfoFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
Labels: enhancement, api-v2

#790 Handle folder force access with errors
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/AccessDeniedBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: enhancement, api-v2

#801 Api v2 upload
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
  app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt
  app/src/main/java/com/infomaniak/drive/data/models/upload/UploadSegment.kt
  app/src/main/java/com/infomaniak/drive/data/models/upload/UploadSession.kt
  app/src/main/java/com/infomaniak/drive/data/models/upload/ValidChunks.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
  app/src/main/java/com/infomaniak/drive/data/sync/UploadMigration.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsActivitiesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomeActivitiesFragment.kt
Labels: feature, api-v2

#817 Update archiveuuid with api update
  app/src/main/java/com/infomaniak/drive/data/models/ArchiveUUID.kt
Labels: bug, api-v2

#816 remove deprecated type in DriveUJser and UserFileAccess and add role …
  app/src/main/java/com/infomaniak/drive/data/models/DriveUser.kt
  app/src/main/java/com/infomaniak/drive/data/models/Share.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/SharedItemsAdapter.kt
Labels: enhancement, api-v2

#815 Fix move button from pictures fragment with api v2
  app/src/main/java/com/infomaniak/drive/ui/fileList/SelectFolderActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesFragment.kt
Labels: bug, api-v2

#819 Fix download offline with an inexistant realm file
  app/src/main/java/com/infomaniak/drive/data/services/DownloadWorker.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
Labels: bug, api-v2

#822 fix add file to my shared test
  app/src/androidTest/java/com/infomaniak/drive/ApiRepositoryTest.kt
  app/src/androidTest/java/com/infomaniak/drive/FileControllerTest.kt
Labels: bug, api-v2

#824 fix download files and save in realm
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
Labels: bug, api-v2

#826 Fix upload sentry issues
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorkerThrowable.kt
  app/src/main/java/com/infomaniak/drive/data/sync/UploadMigration.kt
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/utils/SyncUtils.kt
Labels: bug, enhancement, api-v2

#827 Fix upload worker token when app is in background
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
Labels: bug, enhancement, api-v2

#828 Fix refresh activities after an upload
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
Labels: bug, api-v2

#829 Open a remote folder that does not exist in realm
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
Labels: bug, api-v2

#831 fix upload notification action destination when clicked
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
  app/src/main/java/com/infomaniak/drive/data/sync/UploadNotifications.kt
  app/src/main/java/com/infomaniak/drive/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
Labels: bug, api-v2
