Repository Infomaniak/android-kDrive, pull requests merged in 2022-11, with the labels that each got.

#911 Get file path for all route
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
Labels: bug

#910 Use new file picker class to prompt the user for files
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
Labels: quick

#924 trim folder name
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateFolderFragment.kt
Labels: enhancement

#927 Fix category rights for drive external
  app/src/main/java/com/infomaniak/drive/data/cache/DriveInfosController.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsInfoFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/FileItemUtils.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
Labels: bug

#925 replace setViewPager2 by attachTo
  app/src/main/java/com/infomaniak/drive/ui/login/LoginActivity.kt
Labels: optimization, quick

#928 Fix get categories from DriveExternal
  app/src/main/java/com/infomaniak/drive/data/cache/DriveInfosController.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFiltersFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsInfoFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/SelectCategoriesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: bug

#935 Fix launch app when started without internet connection and after a drive object migration
  app/src/main/java/com/infomaniak/drive/ui/MaintenanceActivity.kt
  app/src/main/java/com/infomaniak/drive/utils/AccountUtils.kt
Labels: bug

#936 Can select ShareWithMe drive and fix using SelectFolderActivity
  app/src/fdroid/java/com/infomaniak/drive/GeniusScanUtils.kt
  app/src/main/java/com/infomaniak/drive/data/cache/DriveInfosController.kt
  app/src/main/java/com/infomaniak/drive/ui/MaintenanceActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/TrashedFileActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SelectFolderActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SelectDriveDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SelectDriveViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SyncSettingsActivity.kt
  app/src/main/java/com/infomaniak/drive/utils/IGeniusScanUtils.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
  app/src/main/res/navigation/main_navigation.xml
  app/src/preprod/java/com/infomaniak/drive/GeniusScanUtils.kt
  app/src/standard/java/com/infomaniak/drive/GeniusScanUtils.kt
Labels: bug, enhancement

#939 make multiselect checkbox not clickable
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
  app/src/main/res/layout/item_file.xml
Labels: bug, quick

#938 replace no-op by Unit
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/GalleryFragment.kt
  app/src/main/java/com/infomaniak/drive/views/com/liuzhenlin/simrv/SlidingItemMenuRecyclerView.kt
Labels: optimization, quick

#943 Fix checkmark flickering on some manufacturer
  app/src/main/res/drawable/ic_checkbox_checked_unchecked.xml
  app/src/main/res/drawable/ic_checkbox_unchecked_checked.xml
Labels: bug, quick

#942 Switch duplicate and move to item in multiselect
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/SharedWithMeMultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/TrashMultiSelectActionsBottomSheetDialog.kt
  app/src/main/res/layout/fragment_bottom_sheet_multi_select_actions.xml
Labels: enhancement, quick

#937 Add category management in multiselect
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/data/models/BulkOperationType.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/CategoryInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/CreateOrEditCategoryFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/CreateOrEditCategoryViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsInfoFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/SelectCategoriesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/SelectCategoriesViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/SharedWithMeMultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/GalleryFragment.kt
  app/src/main/res/layout/fragment_bottom_sheet_multi_select_actions.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: feature
