Repository Infomaniak/android-kDrive, pull requests merged in 2022-02, with the labels that each got.

#487 Fixed folder files icon & color in preview
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/res/layout/view_bottom_sheet_separator.xml
Labels: bug

#488 File activities and comments loader
  app/src/main/java/com/infomaniak/drive/data/models/FileComment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileActivitiesAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileCommentsAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsActivitiesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsCommentsFragment.kt
  app/src/main/res/layout/item_file_activity.xml
  app/src/main/res/layout/item_file_comment.xml
Labels: enhancement

#491 Added VersionCode in File
  app/build.gradle
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileMigration.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
Labels: enhancement

#506 fix file observer before api 29
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
Labels: bug

#505 Fix illegal state exception for move file
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
Labels: bug

#511 Uniformized `UI` into `Ui`
  app/src/main/java/com/infomaniak/drive/ApplicationMain.kt
  app/src/main/java/com/infomaniak/drive/data/models/UiSettings.kt
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/UpdateAvailableBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/ConvertToDropBoxFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/ManageDropboxFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFiltersFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/CategoriesAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/SelectCategoriesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomeFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/AccountUtils.kt
  app/src/main/java/com/infomaniak/drive/views/ShareLinkContainerView.kt
Labels: enhancement

#514 Fix email invitation
  app/src/main/java/com/infomaniak/drive/data/models/ShareableItems.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareAddUserDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareDetailsFragment.kt
Labels: bug

#513 Goto path location
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsInfoFragment.kt
  app/src/main/res/layout/fragment_file_details_infos.xml
Labels: feature

#520 Clean preview code
  app/src/main/java/com/infomaniak/drive/data/models/UiSettings.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/ColorFolderBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPictureFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewVideoFragment.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
Labels: enhancement

#521 Fixed videos & musics in Preview
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewVideoFragment.kt
Labels: bug

#527 Rights migration, temporary fix to v2
  app/src/main/java/com/infomaniak/drive/ApplicationMain.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileMigration.kt
  app/src/main/java/com/infomaniak/drive/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/SwitchDriveDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/SwitchUserActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/login/MigrationActivity.kt
  app/src/main/java/com/infomaniak/drive/utils/AccountUtils.kt
Labels: bug

#529 Handled `Critical` code smells on SonarCloud
  app/src/androidTest/java/com/infomaniak/drive/ApiRepositoryTest.kt
  app/src/main/java/com/infomaniak/drive/utils/AccountUtils.kt
Labels: bug

#533 fix filedetails navigation to parent folder content in bottomnavigation
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsInfoFragment.kt
Labels: bug

#548 Fix RestoreTrashFile API call
  app/src/androidTest/java/com/infomaniak/drive/ApiRepositoryTest.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/TrashViewModel.kt
Labels: bug

#543 Handled some `Minor` code smells on SonarCloud
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareLinkSettingsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/SharedItemsAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPictureFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SyncSettingsActivity.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
  app/src/main/java/com/infomaniak/drive/views/com/liuzhenlin/simrv/SlidingItemMenuRecyclerView.kt
Labels: enhancement

#535 Refactor `UploadWorker.initUploadFile`
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
Labels: enhancement

#549 Cleaned code
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/NewFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/InformationBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/TrashedFileActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
  app/src/main/java/com/infomaniak/drive/views/SelectBottomSheetDialog.kt
Labels: enhancement

#550 Set logs scope level to WARNING
  app/src/main/java/com/infomaniak/drive/data/cache/FileMigration.kt
Labels: enhancement

#554 Fixed rights when creating a Common folder
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
Labels: bug

#541 Fix bulk selection for offline and favorite
  app/src/main/java/com/infomaniak/drive/data/models/BulkOperationType.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/ActionMultiSelectBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/res/layout/fragment_bottom_sheet_action_multi_select.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug

#556 fix file thumbnail for import
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
Labels: bug

#545 Refactor methods to reduce cognitive complexity
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/DownloadProgressDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/ManageDropboxFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareLinkSettingsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/PermissionsAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPictureFragment.kt
Labels: enhancement

#560 Refactor + Bumped RealmGradlePlugin to 10.10.1
  app/build.gradle
  app/src/main/java/com/infomaniak/drive/ui/fileList/SelectFolderActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SelectFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
  app/src/main/res/navigation/select_folder.xml
  build.gradle
Labels: enhancement

#558 Adding logs to get more information in sync media folders
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
Labels: bug, documentation

#577 Replace file for sync offline conflict from upload task
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
  app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt
Labels: bug

#581 Fix open with offline file
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
Labels: bug, enhancement

#580 fix bug on file share settings
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareViewModel.kt
Labels: bug

#585 Remove useless
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/TrashedFileActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/LastFilesAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SyncSettingsActivity.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
Labels: enhancement

#562 More SelectFolder refactor
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SelectFolderActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SelectMediaFoldersDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SyncSettingsActivity.kt
  app/src/main/java/com/infomaniak/drive/utils/DrivePermissions.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/navigation/select_folder.xml
Labels: enhancement

#588 refactor deleteFileFromFavorites in MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
Labels: enhancement

#528 Matomo integration
  app/build.gradle
  app/src/androidTest/java/com/infomaniak/drive/ApiRepositoryTest.kt
  app/src/main/java/com/infomaniak/drive/ApplicationMain.kt
  app/src/main/java/com/infomaniak/drive/data/models/BulkOperationType.kt
  app/src/main/java/com/infomaniak/drive/ui/BaseActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/SwitchDriveDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/SwitchUserActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateCommonFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateDropBoxFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreatePrivateFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/ActionMultiSelectBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/CategoryInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/SelectPermissionBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/SyncConfigureBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/TrashedFileActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/ManageDropboxFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFiltersFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SelectFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/CreateOrEditCategoryFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsCommentsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/SelectCategoriesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareAddUserDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareLinkSettingsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewVideoFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/TrashFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SyncSettingsActivity.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/java/com/infomaniak/drive/utils/MatomoUtils.kt
  app/src/main/java/com/infomaniak/drive/utils/TabViewPagerUtils.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
  app/src/main/java/com/infomaniak/drive/views/ShareLinkContainerView.kt
Labels: feature

#589 Fixed BottomNavigation bar icon issue
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/UpdateAvailableBottomSheetDialog.kt
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/navigation/select_folder.xml
Labels: bug

#559 remove Locale
  app/src/main/java/com/infomaniak/drive/data/models/BulkOperationType.kt
  app/src/main/java/com/infomaniak/drive/data/models/FileActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/SelectPermissionBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesAdapter.kt
  app/src/main/java/com/infomaniak/drive/utils/MatomoUtils.kt
Labels: enhancement

#441 Android UI tests
  .github/workflows/android.yml
  app/build.gradle
  app/src/androidTest/java/com/infomaniak/drive/ApiRepositoryTest.kt
  app/src/androidTest/java/com/infomaniak/drive/FileControllerTest.kt
  app/src/androidTest/java/com/infomaniak/drive/KDriveTest.kt
  app/src/androidTest/java/com/infomaniak/drive/ui/FileItemUiTest.kt
  app/src/androidTest/java/com/infomaniak/drive/ui/FileListUiTest.kt
  app/src/androidTest/java/com/infomaniak/drive/ui/HomeUiTest.kt
  app/src/androidTest/java/com/infomaniak/drive/ui/MenuUiTest.kt
  app/src/androidTest/java/com/infomaniak/drive/utils/ApiTestUtils.kt
  app/src/androidTest/java/com/infomaniak/drive/utils/Env-Exemple.kt
  app/src/androidTest/java/com/infomaniak/drive/utils/UiTestUtils.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/utils/AccountUtils.kt
  build.gradle
Labels: enhancement

#571 add currentFile to the interface
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
Labels: enhancement

#587 Refactor file details view model
  app/src/androidTest/java/com/infomaniak/drive/ui/HomeUiTest.kt
  app/src/main/java/com/infomaniak/drive/data/models/BulkOperationType.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/SelectPermissionBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/PicturesAdapter.kt
Labels: enhancement

#590 Cleaned tests code
  .github/workflows/android.yml
  app/build.gradle
  app/src/androidTest/java/com/infomaniak/drive/FileControllerTest.kt
  app/src/androidTest/java/com/infomaniak/drive/ui/FileItemUiTest.kt
  app/src/androidTest/java/com/infomaniak/drive/ui/FileListUiTest.kt
  app/src/androidTest/java/com/infomaniak/drive/ui/HomeUiTest.kt
  app/src/androidTest/java/com/infomaniak/drive/ui/MenuUiTest.kt
  app/src/androidTest/java/com/infomaniak/drive/utils/ApiTestUtils.kt
Labels: enhancement

#598 Fixed `Open with` so it matches all mime types
  app/src/main/AndroidManifest.xml
Labels: bug

#595 Tests randomize category name
  app/src/androidTest/java/com/infomaniak/drive/ApiRepositoryTest.kt
  app/src/androidTest/java/com/infomaniak/drive/FileControllerTest.kt
  app/src/androidTest/java/com/infomaniak/drive/KDriveTest.kt
  app/src/androidTest/java/com/infomaniak/drive/ui/FileItemUiTest.kt
  app/src/androidTest/java/com/infomaniak/drive/ui/FileListUiTest.kt
  app/src/androidTest/java/com/infomaniak/drive/ui/HomeUiTest.kt
  app/src/androidTest/java/com/infomaniak/drive/ui/MenuUiTest.kt
  app/src/androidTest/java/com/infomaniak/drive/utils/ApiTestUtils.kt
  app/src/main/java/com/infomaniak/drive/utils/MatomoUtils.kt
Labels: enhancement

#593 Clean code
  app/src/androidTest/java/com/infomaniak/drive/ApiRepositoryTest.kt
  app/src/main/java/com/infomaniak/drive/ApplicationMain.kt
  app/src/main/java/com/infomaniak/drive/ui/OnlyOfficeActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/PermissionsAdapter.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
Labels: enhancement

#561 New Select folder view
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SelectFolderActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SyncSettingsActivity.kt
Labels: enhancement, optimization

#596 Refactor UploadWorker
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorkerThrowable.kt
Labels: enhancement

#591 Refactor Extensions.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/java/com/infomaniak/drive/utils/FileItemUtils.kt
Labels: enhancement
