Repository Infomaniak/android-kDrive, pull requests merged in 2023-01, with the labels that each got.

#960 Fix: file moved stays in favorites file list
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
Labels: bug

#965 Fix when click on checkbox in gridmode
  app/src/main/res/layout/cardview_file_grid.xml
  app/src/main/res/layout/cardview_folder_grid.xml
Labels: bug

#949 Add external import progress
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileMigration.kt
  app/src/main/java/com/infomaniak/drive/data/models/Action.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/data/models/MqttAction.kt
  app/src/main/java/com/infomaniak/drive/data/models/MqttNotification.kt
  app/src/main/java/com/infomaniak/drive/data/models/Notification.kt
  app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt
  app/src/main/java/com/infomaniak/drive/data/models/file/FileExternalImport.kt
  app/src/main/java/com/infomaniak/drive/data/services/BulkOperationWorker.kt
  app/src/main/java/com/infomaniak/drive/data/services/MqttClientWrapper.kt
  app/src/main/java/com/infomaniak/drive/data/sync/UploadMigration.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
  app/src/main/java/com/infomaniak/drive/utils/FileItemUtils.kt
  app/src/main/java/com/infomaniak/drive/utils/RealmModules.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
  app/src/main/res/layout/cardview_folder_grid.xml
  app/src/main/res/layout/view_file_info_actions.xml
  app/src/main/res/values-it/strings.xml
Labels: feature

#969 Auto-update copyright year when updating file
  .idea/copyright/Infomaniak_Open_Source.xml
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileActivitiesAdapter.kt
  app/src/main/res/layout/cardview_file_grid.xml
  app/src/main/res/layout/cardview_folder_grid.xml
Labels: optimization

#972 fix: delete a photo already deleted with a query result null
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
Labels: bug, quick
