Repository Infomaniak/android-kDrive, pull requests merged in 2023-10, with the labels that each got.

#1037 Migrate to sentrylog
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileMigration.kt
  app/src/main/java/com/infomaniak/drive/data/documentprovider/CloudStorageProvider.kt
  app/src/main/java/com/infomaniak/drive/data/services/DownloadWorker.kt
  app/src/main/java/com/infomaniak/drive/data/services/MqttClientWrapper.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorkerThrowable.kt
  app/src/main/java/com/infomaniak/drive/data/sync/MediaObserverService.kt
  app/src/main/java/com/infomaniak/drive/data/sync/MediaObserverWorker.kt
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/AccountUtils.kt
  app/src/main/java/com/infomaniak/drive/utils/SyncUtils.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
  app/src/standard/java/com/infomaniak/drive/DriveMessagingService.kt
  app/src/standard/java/com/infomaniak/drive/GeniusScanUtils.kt
Labels: enhancement

#1038 feat: Add more sentryLog & refactor
  app/src/main/java/com/infomaniak/drive/data/services/DownloadWorker.kt
Labels: enhancement

#1039 Fix invalid foreground service type exception
  app/src/main/java/com/infomaniak/drive/data/services/BulkOperationWorker.kt
  app/src/main/java/com/infomaniak/drive/data/services/DownloadWorker.kt
  app/src/main/java/com/infomaniak/drive/utils/BulkOperationsUtils.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/java/com/infomaniak/drive/utils/SyncUtils.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
Labels: bug

#1052 Fix when many scan pages
  app/build.gradle
  app/src/standard/java/com/infomaniak/drive/GeniusScanUtils.kt
Labels: bug

#1050 Replace kotlin extension with view bindings in SelectFolderActivity and related
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SelectFolderActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SelectFolderFragment.kt
  app/src/main/res/layout/activity_select_folder.xml
Labels: enhancement

#1051 Replace kotlin extension with view bindings when creating new folders
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateCommonFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateDropBoxFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreatePrivateFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/NewFolderFragment.kt
Labels: enhancement

#1053 Replace kotlin extension with view bindings in filesharing views
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareAddUserDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareLinkSettingsFragment.kt
Labels: enhancement

#1054 Replace kotlin extension with view bindings in info bottom sheets
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/AccessDeniedBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/ColorFolderUpgradeBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/DriveBlockedBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/DriveMaintenanceBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/DropBoxBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/DropBoxResultBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/InformationBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/NotSupportedExtensionBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/SecureLinkShareBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/SyncAfterMigrationBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/SyncConfigureBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/UpdateAvailableBottomSheetDialog.kt
Labels: enhancement

#1055 Replace kotlin extension with view bindings in SelectBottomSheetDialog
  app/src/main/java/com/infomaniak/drive/ui/SwitchDriveDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/SearchFilterTypeBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SortFilesBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SelectIntervalTypeBottomSheetAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SelectIntervalTypeBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SelectSaveDateBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/views/SelectBottomSheetDialog.kt
Labels: enhancement

#1056 Replace kotlin extension with view bindings in the 3 full screen bottom sheet left
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/SelectPermissionBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SelectDriveDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SelectMediaFoldersDialog.kt
Labels: enhancement

#1058 Add some missing `apply { … }`
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/AccessDeniedBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/NotSupportedExtensionBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareAddUserDialog.kt
Labels: enhancement

#1059 Replace kotlin extension with view bindings in SaveExternalFilesActivity
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
Labels: enhancement

#1048 Global refactor
  app/src/main/java/com/infomaniak/drive/data/api/ProgressRequestBody.kt
  app/src/main/java/com/infomaniak/drive/data/api/ProgressResponseBody.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/DownloadProgressDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPDFFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/PreviewPDFUtils.kt
Labels: enhancement

#1049 Handle preview file protected
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPDFFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/PreviewPDFUtils.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1063 Replace kotlin extension with view bindings in MigrationActivity
  app/src/main/java/com/infomaniak/drive/ui/login/MigrationActivity.kt
Labels: enhancement

#1061 fix: Delete after sync does'nt work
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
Labels: bug

#1071 Replace kotlinx extentsion by viewBinding for dropbox
  app/src/main/java/com/infomaniak/drive/ui/fileList/ConvertToDropBoxFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/ManageDropboxFragment.kt
  app/src/main/java/com/infomaniak/drive/views/ShareLinkContainerView.kt
  app/src/main/res/layout/fragment_manage_dropbox.xml
Labels: optimization

#1073 Replace kotinx extension with ViewBinding for categories
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/CategoryInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/CategoriesAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/CreateOrEditCategoryAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/CreateOrEditCategoryFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/SelectCategoriesFragment.kt
  app/src/main/java/com/infomaniak/drive/views/CategoriesContainerView.kt
  app/src/main/java/com/infomaniak/drive/views/CategoryIconView.kt
Labels: optimization

#1076 Replace kotlin extension with view bindings in HomeActivitiesFragment
  app/src/main/java/com/infomaniak/drive/ui/home/HomeActivitiesFragment.kt
Labels: enhancement

#1070 Replace kotlin extension with view bindings in GalleryFragment
  app/src/main/java/com/infomaniak/drive/ui/menu/GalleryFragment.kt
Labels: enhancement

#1078 Replace kotlin extension with view bindings in GalleryAdapter
  app/src/main/java/com/infomaniak/drive/ui/menu/GalleryAdapter.kt
Labels: optimization

#1080 Replace kotlin extension with view bindings in MultiSelectActionsBottomSheetDialog
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectActionsBottomSheetDialog.kt
Labels: optimization

#1081 Replace kotlin extension with view bindings in file lists
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FavoritesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/ActivityFilesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomeOfflineFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/FileSubTypeListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/MySharesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/OfflineFileFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/RecentChangesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/SharedWithMeFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/TrashFragment.kt
Labels: enhancement

#1082 Replace kotlin extension with view bindings in MainActivity
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
Labels: enhancement

#1084 Add missing safeBindings in already existing bindings
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/BackgroundSyncPermissionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/MenuGalleryFragment.kt
Labels: enhancement, quick

#1085 Use Core ViewHolder
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalUriAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/CategoriesAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/CreateOrEditCategoryAdapter.kt
Labels: enhancement, quick

#1087 Replace kotlin extension with view bindings in bottom sheets
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/ColorFolderBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/SearchFilterDateBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/TrashedFileActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/GalleryMultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/SharedWithMeMultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/TrashMultiSelectActionsBottomSheetDialog.kt
Labels: enhancement

#1088 2 - Replace kotlinx Extension by ViewBinding in Adapters
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileCommentsAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/PermissionsAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/SharedItemsAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/MediaFoldersAdapter.kt
Labels: optimization

#1089 3 - Replace kotlinx Extension by ViewBinding in Adapters
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/SearchFilterTypeBottomSheetAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPDFAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SelectIntervalTypeBottomSheetAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SelectSaveDateBottomSheetAdapter.kt
  app/src/main/res/layout/fragment_preview_pdf.xml
  app/src/main/res/layout/item_pdf_view.xml
Labels: optimization

#1090 4 - Replace kotlinx by viewBinding in adapters
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileActivitiesAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/AvailableShareableItemsAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/home/LastActivitiesAdapter.kt
Labels: optimization

#1092 Replace kotlinx extension by ViewBinding in DownloadProgressDialog
  app/src/main/java/com/infomaniak/drive/ui/fileList/DownloadProgressDialog.kt
Labels: optimization, quick

#1094 Replace kotlinx extension by ViewBinding in FileShareLinkSettingsfragment
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareLinkSettingsFragment.kt
Labels: optimization, quick

#1093 Replace kotlin extension with view bindings in FileDetails fragments
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsActivitiesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsCommentsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsInfoFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsSubFragment.kt
Labels: optimization

#1091 Replace kotlin extension with view bindings in HomeFragment
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomeFragment.kt
Labels: enhancement

#1096 Replace kotlin extension with view bindings in Extension
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomeFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/MenuFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/res/layout/fragment_file_list.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_menu.xml
Labels: enhancement

#1097 Replace kotlin extension with view bindings in FileInfoActionsView
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
Labels: optimization

#1099 Replace kotlin extension with view bindings in SearchFiltersFragment
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFiltersFragment.kt
Labels: optimization

#1100 Replace kx vb settings
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/AboutSettingsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SettingsFragment.kt
Labels: optimization, quick

#1101 Replace kotlin extension with view bindings in IntroFragment
  app/src/main/java/com/infomaniak/drive/ui/login/IntroFragment.kt
Labels: optimization, quick

#1105 Replace kotlinx extension in Extension.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/UserAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SelectDriveDialog.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/res/layout/cardview_user.xml
Labels: optimization

#1104 Use binding in adapter without kotlin Extensions
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFiltersAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/UserAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SelectDriveDialog.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/res/layout/cardview_user.xml
Labels: optimization

#1098 Replace kotlinx extension by ViewBinding in preview fragments
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewOtherFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPDFFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPictureFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewVideoFragment.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
Labels: optimization

#1103 Replace kx vb views
  app/src/main/java/com/infomaniak/drive/views/DateInputView.kt
  app/src/main/java/com/infomaniak/drive/views/NoItemsLayoutView.kt
  app/src/main/java/com/infomaniak/drive/views/NotEnoughStorageView.kt
  app/src/main/java/com/infomaniak/drive/views/TimeInputView.kt
  app/src/main/java/com/infomaniak/drive/views/UrlDisplayView.kt
  app/src/main/java/com/infomaniak/drive/views/UserAvatarView.kt
Labels: optimization
