Repository Infomaniak/android-kDrive, pull requests merged in 2023-12, with the labels that each got.

#1133 Fix binding npe
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewVideoFragment.kt
Labels: bug

#1137 Fix binding NPE
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressFragment.kt
Labels: bug

#1139 Refactor + fix LaunchActivity
  app/src/main/java/com/infomaniak/drive/ui/LaunchActivity.kt
Labels: bug, enhancement

#1135 Clean UI settings
  app/src/main/java/com/infomaniak/drive/data/models/UiSettings.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
Labels: enhancement

#1149 feat: (ApiV3) 1- Add FolderFilesProvider for api v2
  app/src/androidTest/java/com/infomaniak/drive/FileControllerTest.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FolderFilesProvider.kt
  app/src/main/java/com/infomaniak/drive/data/documentprovider/CloudStorageProvider.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
Labels: enhancement

#1150 feat: (ApiV3) 2- Init api
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FolderFilesProvider.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/data/models/FileAction.kt
  app/src/main/java/com/infomaniak/drive/data/models/file/ListingFiles.kt
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
Labels: enhancement

#1155 Add worker to update app in background
  app/build.gradle
  app/src/main/java/com/infomaniak/drive/MainApplication.kt
  app/src/main/java/com/infomaniak/drive/data/services/AppUpdateWorker.kt
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
Labels: feature

#1157 fix: Several uploads notification
  app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorkerThrowable.kt
Labels: bug

#1158 Feat: Uploads consume less than 30% of ram
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
Labels: enhancement
