Repository Infomaniak/android-kDrive, pull requests merged in 2023-11, with the labels that each got.

#1108 Apiv3-2 remove epic url
  app/build.gradle
Labels: enhancement

#1067 Apiv3-3 most recent changes
  app/src/androidTest/java/com/infomaniak/drive/ApiRepositoryTest.kt
  app/src/androidTest/java/com/infomaniak/drive/FileControllerTest.kt
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/RecentChangesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/RecentChangesViewModel.kt
Labels: feature

#1068 Apiv3-4 clean code for trash
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FavoritesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/RecentChangesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/RecentChangesViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/SharedWithMeFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/TrashFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/TrashViewModel.kt
Labels: feature

#1111 Replace kotlinx Extensions by ViewBinding in FileAdapter and FileItemUtils
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalUriAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/TrashedFileActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapterViewHolder.kt
  app/src/main/java/com/infomaniak/drive/utils/FileItemUtils.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
  app/src/main/java/com/infomaniak/drive/views/ProgressLayoutView.kt
  app/src/main/res/layout/cardview_file_grid.xml
  app/src/main/res/layout/cardview_folder_grid.xml
  app/src/main/res/layout/item_file.xml
  app/src/main/res/layout/view_progress_layout.xml
  app/src/main/res/values/attrs.xml
Labels: optimization

#1069 Apiv3-5 Migrate trash to apiV3
  app/src/androidTest/java/com/infomaniak/drive/ApiRepositoryTest.kt
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/RecentChangesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/TrashViewModel.kt
Labels: feature

#1072 Apiv3-6 Gallery with cursor
  app/src/androidTest/java/com/infomaniak/drive/FileControllerTest.kt
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/GalleryFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/GalleryViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/RecentChangesFragment.kt
Labels: feature

#1102 Apiv3-7 home activities
  app/src/androidTest/java/com/infomaniak/drive/ApiRepositoryTest.kt
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomeActivitiesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomeViewModel.kt
Labels: enhancement, feature

#1110 Apiv3-8 File activities
  app/src/androidTest/java/com/infomaniak/drive/ApiRepositoryTest.kt
  app/src/androidTest/java/com/infomaniak/drive/FileControllerTest.kt
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsActivitiesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsCommentsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsViewModel.kt
Labels: feature

#1112 Apiv3-9 fix duplication data in gallery
  app/src/main/java/com/infomaniak/drive/ui/menu/GalleryAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/GalleryFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/GalleryViewModel.kt
Labels: bug

#1129 Extract import logic in class
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/UploadFilesHelper.kt
Labels: enhancement
