Repository Infomaniak/android-kDrive, pull requests merged in 2023-05, with the labels that each got.

#1005 Improve media folders logic
  app/src/main/java/com/infomaniak/drive/data/models/MediaFolder.kt
  app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateCommonFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/MediaFoldersAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SelectMediaFoldersDialog.kt
  app/src/main/java/com/infomaniak/drive/utils/AccountUtils.kt
  app/src/main/java/com/infomaniak/drive/utils/RebootReceiver.kt
Labels: bug, enhancement

#1006 Fix potential bug if migration + appLock
  app/src/main/java/com/infomaniak/drive/ui/LaunchActivity.kt
Labels: bug

#1008 Clean `requestUser()` code
  app/src/main/java/com/infomaniak/drive/utils/AccountUtils.kt
Labels: optimization

#1012 Rename MainApp
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/drive/MainApplication.kt
  app/src/main/java/com/infomaniak/drive/MatomoDrive.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
Labels: optimization
