Repository Infomaniak/android-kDrive, pull requests merged in 2024-08, with the labels that each got.

#1372 fix: (ApiV3) - the current folder from shared with me root folder is nullable
  app/src/main/java/com/infomaniak/drive/ui/menu/SharedWithMeFragment.kt
Labels: bug, quick

#1373 Add lost default visibility of bottom sheet items
  app/src/main/res/layout/fragment_bottom_sheet_multi_select_actions.xml
  app/src/main/res/layout/view_file_info_actions.xml
Labels: bug, quick

#1375 Rename `DownloadProgress` to `DownloadProgressIndicator`
  app/src/main/java/com/infomaniak/drive/ui/fileList/DownloadProgressDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPDFFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
  app/src/main/res/layout/dialog_download_progress.xml
  app/src/main/res/layout/fragment_preview_others.xml
Labels: enhancement, quick

#1376 Stop capturing mqtt connection lost errors to sentry
  app/src/main/java/com/infomaniak/drive/data/services/MqttClientWrapper.kt
Labels: bug, quick

#1379 fix: Don't select a sharedWithMe as main drive
  app/src/main/java/com/infomaniak/drive/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: bug

#1380 Bump Libs
  app/build.gradle
Labels: optimization

#1377 Add info to sentry when user logout
  app/src/main/java/com/infomaniak/drive/utils/AccountUtils.kt
Labels: enhancement

#1390 Remove useless log to sentry
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorkerThrowable.kt
Labels: enhancement

#1368 Can now upload empty files
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
  app/src/main/java/com/infomaniak/drive/data/documentprovider/CloudStorageProvider.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
Labels: enhancement

#1396 Fix no location selected when scanning from shared with me
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
Labels: bug, quick

#1364 Improve error message when file limit is exceeded
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorkerThrowable.kt
  app/src/main/java/com/infomaniak/drive/data/sync/UploadNotifications.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#1398 fix: SharedWithMe folder not always displayed
  app/src/main/java/com/infomaniak/drive/data/documentprovider/CloudStorageProvider.kt
  app/src/main/java/com/infomaniak/drive/ui/home/RootFilesFragment.kt
Labels: bug

#1405 fix: Create a private folder with args
  app/src/main/res/navigation/select_folder.xml
Labels: bug, quick

#1406 fix: Clean gradle cache before to run unit tests from ci
  .github/workflows/android.yml
Labels: quick

#1378 Can now change accounts by double-tap and hold on the profile icon
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/utils/AccountUtils.kt
Labels: feature

#1407 fix: Prevent adding folder itself as child + Inherited actions
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FolderFilesProvider.kt
  app/src/main/java/com/infomaniak/drive/data/models/FileActivity.kt
  app/src/main/java/com/infomaniak/drive/data/models/FileActivityType.kt
Labels: bug

#1404 Fix gallery multiselect actions
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/GalleryMultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectActionsBottomSheetDialog.kt
Labels: bug, quick
