Repository Infomaniak/android-kDrive, pull requests merged in 2024-07, with the labels that each got.

#1335 feat: (ApiV3) Improve sync offline files
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileMigration.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/data/models/file/FileLastActivityBody.kt
  app/src/main/java/com/infomaniak/drive/data/models/file/LastFileAction.kt
  app/src/main/java/com/infomaniak/drive/data/services/DownloadWorker.kt
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/DownloadProgressDialog.kt
  app/src/main/java/com/infomaniak/drive/utils/DownloadOfflineFileManager.kt
  app/src/main/java/com/infomaniak/drive/utils/SyncOfflineUtils.kt
Labels: feature

#1346 Avoid filling up save state bundle endlessly because of the ViewPager2
  app/src/main/res/layout/fragment_preview_slider.xml
Labels: bug

#1352 Remove useless Sentry when deleting a file with a size of 0
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
Labels: enhancement, quick

#1358 Fix several SonarCloud issues
  app/src/main/java/com/infomaniak/drive/ui/OnlyOfficeActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/ConvertToDropBoxFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/ManageDropboxFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareAddUserDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPDFFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/PreviewPDFUtils.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
Labels: enhancement

#1359 Add different labels for personal folders depending on subscription type
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/data/models/drive/Drive.kt
  app/src/main/java/com/infomaniak/drive/ui/home/RootFilesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/MenuItemView.kt
  app/src/main/java/com/infomaniak/drive/utils/AccountUtils.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, quick

#1365 Potential fix of bug allowing a scan to be saved in invalid location
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
Labels: bug, quick
