Repository Infomaniak/android-kDrive, pull requests merged in 2024-09, with the labels that each got.

#1414 Fix external imports not being displayed in API V3
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
Labels: bug, quick

#1411 Fix an IllegalStateException if the network change when the fragment is being detached
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
Labels: bug, quick

#1412 Fix crash when opening multiselect for the first time
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
Labels: bug, quick

#1413 Fix upload shortcut bugged in API V3
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
Labels: bug, quick

#1410 Remove useless captured sentry
  app/src/standard/java/com/infomaniak/drive/GeniusScanUtils.kt
Labels: enhancement, quick

#1392 03 Add File shared list actions
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileShared/FileSharedActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileShared/FileSharedListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileShared/FileSharedPreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileShared/FileSharedViewModel.kt
  app/src/main/java/com/infomaniak/drive/utils/PreviewUtils.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
  app/src/main/res/drawable/ic_menu_download.xml
  app/src/main/res/layout/activity_file_shared.xml
  app/src/main/res/menu/file_list_menu.xml
  app/src/main/res/navigation/file_shared_navigation.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: feature

#1393 04 Rename `fileShared` files to `publicShare`files
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/ui/BasePreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicSharePasswordFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicSharePreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareViewModel.kt
  app/src/main/java/com/infomaniak/drive/utils/FilePresenter.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
  app/src/main/res/layout/activity_public_share.xml
  app/src/main/res/layout/fragment_preview_slider.xml
  app/src/main/res/layout/fragment_public_share_password.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/navigation/public_share_navigation.xml
Labels: enhancement

#1394 05 Add file action bottom sheet
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/ui/BasePreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/BaseDownloadProgressDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/DownloadProgressDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewDownloadProgressDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/OnPublicShareItemClickListener.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareFileActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicSharePreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareViewModel.kt
  app/src/main/java/com/infomaniak/drive/views/ExternalFileInfoActionsView.kt
  app/src/main/res/layout/fragment_bottom_sheet_public_share_file_actions.xml
  app/src/main/res/layout/view_external_file_info_actions.xml
  app/src/main/res/navigation/public_share_navigation.xml
Labels: feature

#1395 06 Close the app and display a toast if the `init` route timed-out
  app/src/main/java/com/infomaniak/drive/ui/LaunchActivity.kt
Labels: enhancement, feature

#1402 07 Public Share fix multiselection
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectManager.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/SharedWithMeFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/TrashFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareMultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareViewModel.kt
Labels: feature

#1415 Do not log deleteTokenError to sentry
  app/src/main/java/com/infomaniak/drive/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/drive/utils/AccountUtils.kt
Labels: enhancement, quick

#1417 08 manage password protected share
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/drive/data/api/ErrorCode.kt
  app/src/main/java/com/infomaniak/drive/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PasswordDialogFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicSharePasswordFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareViewModel.kt
  app/src/main/res/layout/fragment_public_share_password.xml
  app/src/main/res/navigation/public_share_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1419 10 Add new branding design on empty views
  app/src/main/res/drawable-night/ic_app_logos.xml
  app/src/main/res/drawable/ic_app_logos.xml
  app/src/main/res/layout/fragment_public_share_outdated_link.xml
  app/src/main/res/layout/fragment_public_share_password.xml
Labels: feature

#1420 11 Manage read only shares
  app/src/main/java/com/infomaniak/drive/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewOtherFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicSharePasswordFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicSharePreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareViewModel.kt
  app/src/main/res/navigation/public_share_navigation.xml
Labels: feature

#1433 Fix wrong translation for leaveShare
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
Labels: bug, quick

#1435 fix: Ensure to finish activity in the MainThread from SyncSettingsActivity
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SyncSettingsActivity.kt
Labels: bug

#1439 fix: Import files doesn't work sometimes + more logs
  app/src/main/java/com/infomaniak/drive/ui/addFiles/ImportFilesDialog.kt
Labels: bug
