Repository Infomaniak/android-kDrive, pull requests merged in 2024-01, with the labels that each got.

#1160 Fix snackbar still being displayed after successful update
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
Labels: bug

#1163 Fix: Upload relaunch several times
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
  app/src/main/java/com/infomaniak/drive/utils/SyncUtils.kt
Labels: bug

#1152 feat: (ApiV3) 4- Fix Activities + refactor
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FolderFilesProvider.kt
  app/src/main/java/com/infomaniak/drive/data/models/FileAction.kt
  app/src/main/java/com/infomaniak/drive/data/models/FileActivity.kt
  app/src/main/java/com/infomaniak/drive/data/models/FileActivityType.kt
Labels: enhancement, quick

#1153 feat: (ApiV3) 5- Add support for thumbnails, onlyoffice and others
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileMigration.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/utils/RealmListParceler.kt
Labels: enhancement, quick

#1154 feat: (ApiV3) 6- Improve activities manager
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileMigration.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FolderFilesProvider.kt
Labels: enhancement, quick

#1174 Fix: Size column missing (Upload several time) + more upload sentry logs
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
Labels: bug, enhancement

#1175 Fix NPE in PreviewSliderFragment
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
Labels: bug

#1178 Fix: Test deleteAddedFileFromAPI
  app/src/androidTest/java/com/infomaniak/drive/FileControllerTest.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
Labels: bug
