Repository Infomaniak/android-kDrive, pull requests merged in 2024-04, with the labels that each got.

#1250 Handle Activity recreation when choosing Files to upload
  app/src/main/java/com/infomaniak/drive/MatomoDrive.kt
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/ImportFilesDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/UploadFilesHelper.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/SharedWithMeFragment.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: bug

#1265 Add back missing isVisible import in order to build the project
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/TrashMultiSelectActionsBottomSheetDialog.kt
Labels: bug, quick

#1267 Use a single observer instead of two
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
Labels: optimization, quick

#1269 Enhancement: (ApiV3) - Improve master after merge into ApiV3
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/UploadFilesHelper.kt
Labels: enhancement, quick

#1273 Remove useless sentries
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
  app/src/main/java/com/infomaniak/drive/utils/SyncUtils.kt
Labels: enhancement

#1263 Feat: (ApiV3) - Migrate File to File with uid field
  app/src/main/java/com/infomaniak/drive/MainApplication.kt
  app/src/main/java/com/infomaniak/drive/data/api/FileDeserialization.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileMigration.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
Labels: feature

#1264 Fix: (ApiV3) - After the root you lose folder data
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/home/RootFilesFragment.kt
Labels: bug

#1268 Fix: (ApiV3) - Trash pagination does not stop even though the view is destroyed
  app/src/main/java/com/infomaniak/drive/ui/menu/TrashViewModel.kt
Labels: bug

#1274 fix: (ApiV3) - Avoid activities from root, it throws an http error 401
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
Labels: bug, quick

#1266 Display folder subtitle when inside the organization file
  app/src/main/java/com/infomaniak/drive/data/models/drive/Drive.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
  app/src/main/res/layout/fragment_file_list.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature, quick

#1277 Update CI steps names
  .github/workflows/android.yml
Labels: optimization

#1280 fix: Root files blink
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/home/RootFilesFragment.kt
Labels: bug, enhancement

#1291 Fix sync random folders
  app/src/main/java/com/infomaniak/drive/data/models/MediaFolder.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
Labels: bug

#1292 Fix: Cancel the fetch recent media task if needed
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
Labels: bug, quick

#1290 fix: New folders are auto-synchronized
  app/src/main/java/com/infomaniak/drive/data/documentprovider/CloudStorageProvider.kt
  app/src/main/java/com/infomaniak/drive/utils/MediaFoldersProvider.kt
Labels: bug

#1287 Block edition of office files when user has no connection and display toast to inform the user
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsCommentsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
Labels: enhancement

#1285 Feat: (ApiV3) - CloudStorage for apiV3 + enhancement load with pagination
  app/src/main/java/com/infomaniak/drive/data/cache/FolderFilesProvider.kt
  app/src/main/java/com/infomaniak/drive/data/documentprovider/CloudStorageProvider.kt
  app/src/main/java/com/infomaniak/drive/data/documentprovider/DocumentCursor.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileActivitiesAdapter.kt
Labels: bug, enhancement

#1294 fix: VisibilityType doesn't return the dropbox visibility type
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
Labels: bug, quick

#1278 Remove home wide searchbar for the toolbar menu icon
  app/src/main/java/com/infomaniak/drive/ui/home/HomeFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/LastActivitiesAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/home/RootFilesFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_activities.xml
  app/src/main/res/layout/item_last_activities_subtitle.xml
Labels: enhancement
