Repository Infomaniak/android-kDrive, pull requests merged in 2024-05, with the labels that each got.

#1293 Fix visibility of dialog when we upload files
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/ImportFilesDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/UploadFilesHelper.kt
Labels: bug

#1296 Fix: (ApiV3) Move a file throw a NullPointerException
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
Labels: bug, quick

#1297 Fix: Import files can have a coroutine competition problem
  app/src/main/java/com/infomaniak/drive/ui/addFiles/ImportFilesDialog.kt
Labels: bug, quick

#1288 Fix the shortcut support so the user don't have to connect to have help
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/drive/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/login/LoginActivity.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: enhancement

#1298 Adding margins when we have an inset
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPDFActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/views/PreviewHeaderView.kt
Labels: enhancement

#1303 Do not let the fileList be in grid mode
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
Labels: bug, quick

#1306 Fix: create a dropbox folder no longer works since driveV2
  app/src/main/java/com/infomaniak/drive/data/cache/DriveInfosController.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/NewFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/NewFolderViewModel.kt
Labels: bug

#1310 Fix: (ApiV3) home blink
  app/src/main/java/com/infomaniak/drive/ui/home/HomeActivitiesFragment.kt
Labels: bug

#1312 Fix wrong snackbar being displayed when importing files on low memory
  app/src/main/java/com/infomaniak/drive/ui/addFiles/ImportFilesDialog.kt
Labels: bug, quick

#1317 Bump versions
  app/build.gradle
  build.gradle
Labels: optimization

#1315 Fix contacts being added when “done” is clicked repeatedly when sharing a folder
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/AvailableShareableItemsAdapter.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/res/layout/fragment_bottom_sheet_file_share.xml
  app/src/main/res/layout/fragment_file_share_details.xml
Labels: bug, quick

#1319 Format AvailableShareableItemsAdapter code
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/AvailableShareableItemsAdapter.kt
Labels: optimization, quick

#1316 Fix tab inserting the toString of objects instead of autocompletion when sharing folder
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/AvailableShareableItemsAdapter.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
Labels: bug, quick

#1307 fix: Create a dropbox from a sharedWithMe logout user
  app/src/main/java/com/infomaniak/drive/ui/addFiles/NewFolderFragment.kt
  app/src/main/res/layout/fragment_new_folder.xml
Labels: bug, quick
