Repository Infomaniak/android-kDrive, pull requests merged in 2024-10, with the labels that each got.

#1425 13 Fix pagination bug
  app/src/main/java/com/infomaniak/drive/data/cache/FolderFilesProvider.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareViewModel.kt
Labels: feature, quick

#1426 14 Move file url function to api route
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/drive/data/documentprovider/CloudStorageProvider.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPictureFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewVideoFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/LastActivitiesAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/GalleryAdapter.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/java/com/infomaniak/drive/utils/FileItemUtils.kt
  app/src/main/java/com/infomaniak/drive/utils/PreviewUtils.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
Labels: enhancement, quick

#1441 fix: Syncing a file from an external app via cloud storage doesn't work
  app/src/main/java/com/infomaniak/drive/data/documentprovider/CloudStorageProvider.kt
Labels: bug

#1427 15 Refactor executeDownloadActions
  app/src/main/java/com/infomaniak/drive/ui/publicShare/OnPublicShareItemClickListener.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareFileActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicSharePreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareViewModel.kt
Labels: enhancement

#1429 16 Send sharedWithMe deeplink to the browser
  app/src/main/java/com/infomaniak/drive/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicSharePasswordFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
Labels: feature

#1434 18 Sort files so folders are in first like in the realm sort
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareViewModel.kt
Labels: enhancement, quick

#1436 19 Clean navigation args
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/ui/BasePreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareFileActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicSharePreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareViewModel.kt
  app/src/main/java/com/infomaniak/drive/utils/FilePresenter.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/navigation/public_share_navigation.xml
Labels: optimization

#1437 19.5 Fix actions for shared with me files
  app/src/main/java/com/infomaniak/drive/data/documentprovider/CloudStorageProvider.kt
  app/src/main/java/com/infomaniak/drive/ui/BasePreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPDFActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/PreviewUtils.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
Labels: bug

#1438 20 Add matomo in public share feature
  app/src/main/java/com/infomaniak/drive/MatomoDrive.kt
  app/src/main/java/com/infomaniak/drive/ui/BasePreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/BaseDownloadProgressDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPDFActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/OnPublicShareItemClickListener.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareMultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicSharePasswordFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicSharePreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/java/com/infomaniak/drive/utils/FilePresenter.kt
  app/src/main/java/com/infomaniak/drive/utils/PreviewUtils.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
Labels: enhancement

#1442 21 Add create account ad bottomsheet
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/drive/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/ObtainKDriveAdBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/OnPublicShareItemClickListener.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareListFragment.kt
  app/src/main/java/com/infomaniak/drive/views/ExternalFileInfoActionsView.kt
  app/src/main/res/drawable-night/illu_obtain_kdrive.xml
  app/src/main/res/drawable/illu_obtain_kdrive.xml
  app/src/main/res/layout/fragment_bottom_sheet_obtain_kdrive_ad.xml
  app/src/main/res/layout/fragment_public_share_password.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/navigation/public_share_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature

#1445 Fix conflict between SwipeRefresh and FastScroller in gallery
  app/src/main/java/com/infomaniak/drive/ui/menu/GalleryFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/MenuGalleryFragment.kt
  app/src/main/res/layout/fragment_gallery.xml
  app/src/main/res/layout/fragment_menu_gallery.xml
Labels: bug

#1446 Add colorable right to File
  app/src/main/java/com/infomaniak/drive/data/cache/FileMigration.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/data/models/Rights.kt
Labels: enhancement

#1448 Fix details files count
  app/src/main/java/com/infomaniak/drive/data/models/FileCount.kt
Labels: bug

#1450 Rename the english version of the traduction that have been left incorrect
  app/src/main/res/values/strings.xml
Labels: enhancement, quick

#1453 Fix shared with me list not updated for colored folder
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
Labels: bug

#1456 23 Public share clean code
  app/src/main/java/com/infomaniak/drive/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicSharePasswordFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareViewModel.kt
  app/src/main/java/com/infomaniak/drive/utils/PublicShareUtils.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
Labels: enhancement

#1457 24 Public share manage importation
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareViewModel.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1459 Remove occurences to `_inherited` activites as it is now obsolete
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FolderFilesProvider.kt
  app/src/main/java/com/infomaniak/drive/data/models/FileActivity.kt
  app/src/main/java/com/infomaniak/drive/data/models/FileActivityType.kt
Labels: enhancement, quick

#1460 Update translations of the "Common folders" folder's name
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: quick

#1461 Display the Sync import canceling button at the view creation
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressFragment.kt
Labels: bug, quick

#1467 Fix mqtt for external imports
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/data/models/MqttAction.kt
  app/src/main/java/com/infomaniak/drive/data/models/MqttNotification.kt
  app/src/main/java/com/infomaniak/drive/data/services/MqttClientWrapper.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
Labels: bug

#1472 fix(InfiniteLoading): Fix inifinite loading in SyncSettingsActivity and add a sentry
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SyncSettingsActivity.kt
Labels: bug, quick
