Repository Infomaniak/android-kDrive, pull requests merged in 2024-06, with the labels that each got.

#1323 Update of Genius Scan library
  app/build.gradle
Labels: enhancement, quick

#1324 fix: Stop logging full deeplink path in Matomo
  app/src/main/java/com/infomaniak/drive/MatomoDrive.kt
  app/src/main/java/com/infomaniak/drive/ui/LaunchActivity.kt
Labels: bug

#1329 Fix grid mode disabling when browsing folders
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
Labels: bug, quick

#1330 Remove the gap between the bottom sheet and the bottom of the screen
  app/src/main/java/com/infomaniak/drive/utils/PreviewUtils.kt
  app/src/main/res/layout/fragment_preview_slider.xml
Labels: enhancement

#1336 Get file last modified date from URI when coming from kMail attachment
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/utils/SyncUtils.kt
Labels: enhancement

#1342 Fix upload stopping because of closed realm instance
  app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
Labels: bug

#1339 Add missing `enableOnBackInvokedCallback` in Manifest
  app/src/main/AndroidManifest.xml
Labels: optimization
