Repository Infomaniak/android-kDrive, pull requests merged in 2024-02, with the labels that each got.

#1181 Fix: MQTT with new version 4.2
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/drive/data/services/BulkOperationWorker.kt
  app/src/main/java/com/infomaniak/drive/data/services/MqttClientWrapper.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
Labels: bug, feature

#1176 (1- ApiV3) Feat: Search
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchViewModel.kt
Labels: feature

#1177 (2- ApiV3) Fix: cursor
  app/src/main/java/com/infomaniak/drive/data/api/CursorApiResponse.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FolderFilesProvider.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/TrashViewModel.kt
Labels: enhancement

#1187 fix: Display progress notification immediately on work startup
  app/src/main/java/com/infomaniak/drive/data/services/BulkOperationWorker.kt
Labels: bug

#1191 File display name function for future branches
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, quick

#1190 Fix: (ApiV3) - Restore activities if needed from home activities
  app/src/main/java/com/infomaniak/drive/ui/home/HomeActivitiesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomeViewModel.kt
Labels: bug

#1194 Add UNKOWN visibility type
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
Labels: bug, quick

#1199 feat: (Apiv3) Search - Replace from/until by modified_after/modified_before
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
Labels: feature

#1205 Fix missing "My files" name in FileListFragment
  app/src/main/java/com/infomaniak/drive/utils/FilePresenter.kt
Labels: bug, quick

#1206 Some Sonar fix
  app/src/main/java/com/infomaniak/drive/data/services/MqttClientWrapper.kt
Labels: enhancement

#1200 Change the upload folder at the root with the "private folder"
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/SharedWithMeFragment.kt
Labels: feature

#1203 Compute screen width and height according to the app size and not the device
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
Labels: bug, quick

#1209 Remove upload shortcut ROOT_ID requirements
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
Labels: bug, feature

#1201 Add missing navbar in RootFiles file lists
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
Labels: feature

#1220 Fix strings according to guidelines
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-fr/strings.xml
Labels: bug, quick

#1210 Avoid double click on the sharing button
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
Labels: bug

#1207 Display small fab in Search
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/RootFilesFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/FilePresenter.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/styles.xml
Labels: feature

#1211 We cannot be in the root folder anymore therefore remove multiselect check
  app/src/main/java/com/infomaniak/drive/data/models/drive/Drive.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/FileItemUtils.kt
Labels: feature, dependent

#1212 Remove unnecessary root check to display drive name in FileListFragment
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
Labels: feature, dependent

#1213 Remove external import selected drive display name
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
Labels: feature, dependent

#1214 Remove root check for empty state visibility
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FavoritesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFragment.kt
Labels: feature, dependent

#1216 Leave the method early if we're navigating to ROOT_ID anyway
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
Labels: enhancement, dependent

#1217 We can go back to only checking for OTHER_ROOT_ID because we can't be inside ROOT_ID anymore with v3
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
Labels: feature, dependent

#1218 `destinationId` could never be `null` so we don't need to fallback to `ROOT_ID`
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
Labels: enhancement, dependent

#1219 ROOT_ID would already be disabled because we can't create files in it
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SyncSettingsActivity.kt
Labels: feature, dependent

#1221 Clean code
  app/src/androidTest/java/com/infomaniak/drive/ui/KDriveUiTest.kt
  app/src/main/java/com/infomaniak/drive/data/services/DownloadWorker.kt
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/utils/FileItemUtils.kt
  app/src/main/res/drawable-night/illu_update_required.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_bottom_sheet_information.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_settings_about.xml
  app/src/main/res/layout/item_file_activity.xml
  app/src/main/res/layout/view_menu_item.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#1222 Add `showAboveFab` parameter name
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/ImportFilesDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
Labels: enhancement

#1223 Add `shouldShow` parameter name for `toggleBottomSheet()` & `toggleSystemBar()`
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
Labels: enhancement

#1224 Add no network indicator banner to the root of files and the gallery
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomeFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/RootFilesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/MenuGalleryFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/res/layout/fragment_file_list.xml
  app/src/main/res/layout/fragment_menu_gallery.xml
  app/src/main/res/layout/fragment_root_files.xml
  app/src/main/res/layout/layout_no_network_small.xml
Labels: feature

#1227 Don't use deprecated 'init' function for GeniusScanSDK
  app/src/standard/java/com/infomaniak/drive/GeniusScanUtils.kt
Labels: enhancement, quick

#1232 Remove unsupported sort types
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SortFilesBottomSheetAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/TrashFragment.kt
Labels: bug
