Repository Infomaniak/android-kDrive, pull requests merged in 2024-03, with the labels that each got.

#1238 Temporary fix for incorrect pending files upload count
  app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt
Labels: bug, quick

#1240 Remove shared with me ROOT_ID usage
  app/src/main/java/com/infomaniak/drive/ui/menu/SharedWithMeFragment.kt
Labels: enhancement, quick

#1231 Fix Gallery crash
  app/src/main/java/com/infomaniak/drive/ui/menu/MenuGalleryFragment.kt
Labels: bug

#1230 Update API calls to receive `null` avatars if the users have not set any
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/data/models/DriveUser.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareAddUserDialog.kt
Labels: feature

#1241 When uploading files instantly display progress instead of waiting for a onResume()
  app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomeFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/RootFilesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/MenuFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
Labels: bug, enhancement

#1247 Fix: Sync all media doesn't work and improved media detection
  app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
  app/src/main/java/com/infomaniak/drive/data/sync/MediaObserverWorker.kt
Labels: bug

#1246 Handle upload notification in home when we scan a document
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomeFragment.kt
Labels: bug

#1243 Simplify clear of backstack after selecting back item from bottom navigation because there are no more file lists
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
Labels: quick

#1253 Update wording for refresh token error
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#1244 Tidy offline UI to make it a bit easier to understand
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
Labels: enhancement

#1254 Use `typealias IOFile` everywhere it's needed
  app/src/androidTest/java/com/infomaniak/drive/KDriveTest.kt
  app/src/main/java/com/infomaniak/drive/data/documentprovider/CloudStorageProvider.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt
  app/src/main/java/com/infomaniak/drive/data/services/DownloadWorker.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/FileInfoActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/DownloadProgressDialog.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPictureFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewVideoFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/FileItemUtils.kt
  app/src/main/java/com/infomaniak/drive/utils/MediaUtils.kt
  app/src/main/java/com/infomaniak/drive/utils/SyncOfflineUtils.kt
  app/src/main/java/com/infomaniak/drive/utils/SyncUtils.kt
  app/src/main/java/com/infomaniak/drive/utils/Utils.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
Labels: optimization

#1245 Factorize bottom sheet items
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/MultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/views/BottomSheetItemView.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
  app/src/main/res/color/star_favorites.xml
  app/src/main/res/layout/fragment_bottom_sheet_add_file.xml
  app/src/main/res/layout/fragment_bottom_sheet_multi_select_actions.xml
  app/src/main/res/layout/fragment_bottom_sheet_trashed_file_actions.xml
  app/src/main/res/layout/view_bottom_sheet_item.xml
  app/src/main/res/layout/view_file_info_actions.xml
  app/src/main/res/values/attrs.xml
Labels: enhancement

#1258 Merge the apiv3-ui feature branch to the main apiv3 branch
  .github/workflows/android.yml
  .idea/navEditor.xml
  app/src/androidTest/java/com/infomaniak/drive/ui/EspressoHomeUiTest.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileController.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/data/models/UiSettings.kt
  app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt
  app/src/main/java/com/infomaniak/drive/data/models/drive/Drive.kt
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FavoritesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SortFilesBottomSheetAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomeActivitiesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomeFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomeOfflineFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/RootFilesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/MenuFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/MenuGalleryFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/MenuItemView.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/SharedWithMeFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/TrashFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SyncSettingsActivity.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/java/com/infomaniak/drive/utils/FileItemUtils.kt
  app/src/main/java/com/infomaniak/drive/utils/FilePresenter.kt
  app/src/main/java/com/infomaniak/drive/views/PendingFilesView.kt
  app/src/main/res/drawable/ic_gallery.xml
  app/src/main/res/drawable/ic_gallery_filled.xml
  app/src/main/res/drawable/ic_gallery_unfilled.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/cardview_gallery.xml
  app/src/main/res/layout/fragment_file_list.xml
  app/src/main/res/layout/fragment_gallery.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_activities.xml
  app/src/main/res/layout/fragment_menu.xml
  app/src/main/res/layout/fragment_menu_gallery.xml
  app/src/main/res/layout/fragment_root_files.xml
  app/src/main/res/layout/layout_no_network_small.xml
  app/src/main/res/layout/layout_switch_drive.xml
  app/src/main/res/layout/view_menu_item.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature

#1259 fix: Get current pending upload files throw an exception
  app/src/main/java/com/infomaniak/drive/data/models/UploadFile.kt
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
Labels: bug

#1261 Apiv3: Global refactor
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FileMigration.kt
  app/src/main/java/com/infomaniak/drive/data/documentprovider/CloudStorageProvider.kt
  app/src/main/java/com/infomaniak/drive/data/models/DropBox.kt
  app/src/main/java/com/infomaniak/drive/data/models/FileCategory.kt
  app/src/main/java/com/infomaniak/drive/data/models/FileComment.kt
  app/src/main/java/com/infomaniak/drive/data/models/IpsToken.kt
  app/src/main/java/com/infomaniak/drive/data/models/ShareLink.kt
  app/src/main/java/com/infomaniak/drive/data/models/drive/Category.kt
  app/src/main/java/com/infomaniak/drive/data/models/file/dropbox/DropBoxValidity.kt
  app/src/main/java/com/infomaniak/drive/data/models/upload/UploadSegment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/multiSelect/TrashMultiSelectActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/utils/FilePresenter.kt
  app/src/main/java/com/infomaniak/drive/views/com/liuzhenlin/simrv/SlidingItemMenuRecyclerView.kt
Labels: enhancement, quick
