Repository Infomaniak/android-kDrive, pull requests merged in 2025-05, with the labels that each got.

#1591 feat: Implement fragment navigation module
  app/build.gradle
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SettingsFragment.kt
  settings.gradle
Labels: feature

#1595 fix(BackgroundSyncBattery): Fix crash when asking for background sync permissions the first time
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SyncSettingsActivity.kt
  app/src/main/java/com/infomaniak/drive/utils/DrivePermissions.kt
  app/src/main/java/com/infomaniak/drive/utils/SyncUtils.kt
Labels: bug

#1600 chore: Update app logo icons
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_monochrome.xml
  app/src/main/res/drawable/ic_logo_notification.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: enhancement

#1583 feat: Upgrade to SDK35
  app/build.gradle
  app/src/main/java/com/infomaniak/drive/extensions/InsetsExtensions.kt
  app/src/main/java/com/infomaniak/drive/ui/BasePreviewSliderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/SwitchUserActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/CreateFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/NewFolderFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/dropbox/ManageDropboxFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SearchFiltersFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/SelectFolderActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/CreateOrEditCategoryFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsInfoFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/SelectCategoriesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareDetailsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareLinkSettingsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomeActivitiesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/HomeFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/home/RootFilesFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/login/IntroFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/GalleryFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/MenuGalleryFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/AboutSettingsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SyncSettingsActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareActivity.kt
  app/src/main/java/com/infomaniak/drive/utils/PreviewUtils.kt
  app/src/main/java/com/infomaniak/drive/views/CollapsingSubTitleToolbarBehavior.kt
  app/src/main/java/com/infomaniak/drive/views/PreviewHeaderView.kt
  app/src/main/res/layout/activity_only_office.xml
  app/src/main/res/layout/activity_public_share.xml
  app/src/main/res/layout/activity_save_external_file.xml
  app/src/main/res/layout/activity_select_folder.xml
  app/src/main/res/layout/fragment_file_details.xml
  app/src/main/res/layout/fragment_file_details_infos.xml
  app/src/main/res/layout/fragment_file_list.xml
  app/src/main/res/layout/fragment_file_share_link_settings.xml
  app/src/main/res/layout/fragment_intro.xml
  app/src/main/res/layout/fragment_menu.xml
  app/src/main/res/layout/fragment_root_files.xml
  app/src/main/res/layout/fragment_search_filters.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/view_switch_settings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: feature
