Repository Infomaniak/android-kDrive, pull requests merged in 2025-04, with the labels that each got.

#1577 chore(Sonar): Make sonar happy again
  app/src/main/java/com/infomaniak/drive/ui/dropbox/ConvertToDropboxFragment.kt
Labels: enhancement

#1576 feat: Manage my ksuite quotas locally
  app/src/main/java/com/infomaniak/drive/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/dropbox/DropboxViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileDetails/FileDetailsInfoFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/fileShare/FileShareDetailsFragment.kt
Labels: enhancement

#1571 fix: FileAction actionType incorrectly marked as unknown
  app/src/main/java/com/infomaniak/drive/data/models/FileAction.kt
Labels: bug, quick

#1581 feat: Sync without right for all photo
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SyncSettingsActivity.kt
  app/src/main/java/com/infomaniak/drive/utils/CameraPermissions.kt
  app/src/main/java/com/infomaniak/drive/utils/DrivePermissions.kt
  app/src/main/java/com/infomaniak/drive/utils/NotificationPermission.kt
  app/src/main/res/layout/activity_sync_settings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature
