Repository Infomaniak/android-kDrive, pull requests merged in 2025-09, with the labels that each got.

#1787 chore: Clean useless matrix in android ci github workflow
  .github/workflows/android.yml
Labels: enhancement, quick

#1801 refactor(PublicShare): Use multitask for public share
  app/src/main/java/com/infomaniak/drive/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareListFragment.kt
Labels: enhancement

#1802 refactor(PublicShareApi): Create a new api repository specific to publicShare
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/drive/data/api/PublicShareApiRepository.kt
  app/src/main/java/com/infomaniak/drive/data/cache/FolderFilesProvider.kt
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/FileListViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/preview/PreviewPDFFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareViewModel.kt
  app/src/main/java/com/infomaniak/drive/utils/PreviewUtils.kt
Labels: enhancement

#1816 fix(ExternalFileOpening): Fix a crash when opening a pdf with kDrive
  app/src/main/res/navigation/public_share_navigation.xml
Labels: bug
