Repository Infomaniak/android-kDrive, pull requests merged in 2025-02, with the labels that each got.

#1515 chore: Update to agp 8.7.2
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#1532 feat(MyKSuite-dashboard): Add dashboard
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/drive/MainApplication.kt
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/MyKSuiteViewModel.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/KSuiteDashboardFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/AccountUtils.kt
  app/src/main/java/com/infomaniak/drive/utils/MyKSuiteDataUtils.kt
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: feature

#1535 feat(StorageExceeded): Prompt upgrade bottomsheet when user quotas are exceeded
  app/src/main/java/com/infomaniak/drive/data/models/drive/Drive.kt
  app/src/main/java/com/infomaniak/drive/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/addFiles/AddFileBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
Labels: feature

#1529 fix: Show a snackbar when a conflict error occurs
  app/src/main/java/com/infomaniak/drive/ui/bottomSheetDialogs/TrashedFileActionsBottomSheetDialog.kt
Labels: bug, enhancement, quick

#1480 feat: Allow keyboard navigation
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/MediaFoldersAdapter.kt
  app/src/main/java/com/infomaniak/drive/views/PreviewHeaderView.kt
  app/src/main/res/layout/activity_sync_settings.xml
  app/src/main/res/layout/fragment_bottom_sheet_file_share.xml
  app/src/main/res/layout/fragment_bottom_sheet_select_drive.xml
  app/src/main/res/layout/fragment_bottom_sheet_select_media_folders.xml
  app/src/main/res/layout/fragment_create_folder.xml
  app/src/main/res/layout/fragment_create_or_edit_category.xml
  app/src/main/res/layout/fragment_file_details.xml
  app/src/main/res/layout/fragment_file_list.xml
  app/src/main/res/layout/fragment_file_share_details.xml
  app/src/main/res/layout/fragment_file_share_link_settings.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_manage_dropbox.xml
  app/src/main/res/layout/fragment_new_folder.xml
  app/src/main/res/layout/fragment_preview_slider.xml
  app/src/main/res/layout/fragment_root_files.xml
  app/src/main/res/layout/fragment_search_filters.xml
  app/src/main/res/layout/fragment_select_categories.xml
  app/src/main/res/layout/fragment_select_permission.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_settings_about.xml
  app/src/main/res/layout/layout_switch_drive.xml
  app/src/main/res/layout/view_switch_settings.xml
Labels: feature

#1540 fix(UrlFiles): Fix opening of url files and make the checks case-insensitive
  app/src/main/java/com/infomaniak/drive/data/models/File.kt
  app/src/main/java/com/infomaniak/drive/ui/SaveExternalFilesActivity.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/OnPublicShareItemClickListener.kt
  app/src/main/java/com/infomaniak/drive/ui/publicShare/PublicShareListFragment.kt
  app/src/main/java/com/infomaniak/drive/utils/Extensions.kt
  app/src/main/java/com/infomaniak/drive/utils/FilePresenter.kt
Labels: bug, quick

#1545 fix: Edit button invisible on first file in the list
  app/src/main/java/com/infomaniak/drive/views/PreviewHeaderView.kt
  app/src/main/res/layout/preview_header_view.xml
Labels: bug

#1547 fix: Use 'okHttpClientLongTimeout' for trash emptying instead of 'okHttpClient'
  app/src/main/java/com/infomaniak/drive/data/api/ApiRepository.kt
Labels: quick
