Repository Infomaniak/android-kDrive, pull requests merged in 2025-07, with the labels that each got.

#1684 fix: Fix needlessly mutable types
  app/src/main/java/com/infomaniak/drive/data/services/UploadWorker.kt
  app/src/main/java/com/infomaniak/drive/views/FileInfoActionsView.kt
Labels: quick

#1710 fix: Fix crash caused by Realm closed on wrong thread
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressFragment.kt
  app/src/main/java/com/infomaniak/drive/ui/fileList/UploadInProgressViewModel.kt
Labels: quick

#1717 refactor(SelectMediaFolderViewModel): Replace java's ArrayList by Kotlin's List
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/MediaFoldersAdapter.kt
  app/src/main/java/com/infomaniak/drive/ui/menu/settings/SelectMediaFoldersViewModel.kt
Labels: enhancement

#1720 fix: Fix crash caused by TypeToken of ApiResponse with generic type on upload error
  app/src/main/java/com/infomaniak/drive/data/api/UploadTask.kt
Labels: bug, quick
